Repository openconfig/featureprofiles, pull requests merged in 2023-08, with the labels that each got.

#1967 Remove ISISprotocolEnabledNotRequired deviation
  feature/experimental/isis/ate_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/isis_change_lsp_lifetime_test.go
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/experimental/isis/ate_tests/lsp_updates_test/metadata.textproto
  feature/experimental/isis/otg_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#1928 OTG: RT1.5 BGP Prefix Limit Align the test with ATE
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
Labels: keysight-pr

#1927 OTG: RT1.3 BGP Route Propagation Align the test with ATE
  feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
Labels: keysight-pr

#1914 TE-11.3 backup_nhg_action_test.go
  feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/ate_tests/backup_nhg_action/metadata.textproto
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#1890 gNOI-5.3: Adding chassis component artifact fetch test
  feature/gnoi/system/tests/copying_debug_files_test/README.md
  feature/gnoi/system/tests/copying_debug_files_test/copying_debug_files_test.go
Labels: juniper-pr

#1972 TUN-1.9: GRE inner packet DSCP
  feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/README.md
  feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/metadata.textproto
  feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/tun_acl_dscp_test.go
Labels: juniper-pr, anCX

#1966 Remove IS-IS instance leaf use & update deviation
  feature/experimental/isis/ate_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/experimental/isis/ate_tests/lsp_updates_test/metadata.textproto
  feature/experimental/isis/otg_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2015 Remove testbed port check for binding file
  topologies/binding/binding.go
  topologies/binding/binding_test.go
Labels: nokia-pr

#1903 Sec-3.1 native user
  feature/experimental/security/aaa/kne_tests/tls_authentication_over_grpc_test/metadata.textproto
  feature/experimental/security/aaa/kne_tests/tls_authentication_over_grpc_test/tls_authentication_over_grpc_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#1952 OTG Tests Update - Corrected loss percentage calculation
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go
  feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
  feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
  feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
  feature/gribi/otg_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
  feature/networkinstance/otg_tests/defaults_test/defaults_test.go
  internal/otgutils/print.go
Labels: keysight-pr

#2021 OTG: Align the test TE_13.1 with ATE
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
Labels: keysight-pr

#2043 Default base configs needed for cptx
  topologies/kne/juniper/cptx/config.cfg
Labels: juniper-pr

#2045 updated timeout value to 60seconds for the await call
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Labels: cisco-pr

#1739 RT-5.6 Interface Loopback mode
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/README.md
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/metadata.textproto
Labels: juniper-pr

#1807 RT2.7 isis_interface_passive_test.go
  feature/experimental/isis/otg_tests/isis_interface_passive_test/README.md
  feature/experimental/isis/otg_tests/isis_interface_passive_test/isis_interface_passive_test.go
  feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
Labels: juniper-pr, anCX

#1915 RT-2.8: IS-IS metric style wide not enabled
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/README.md
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/isis_metric_style_wide_not_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
Labels: juniper-pr, anCX

#1917 RT-2.9: IS-IS metric style wide enabled
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/README.md
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/isis_metric_style_wide_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
Labels: juniper-pr, anCX

#1933 OTG TE-2.1 Update - ATE test sync and more
  feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Labels: keysight-pr

#1938 OTG TE-3.7 - Updating flows with multiple ports as destinations
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: keysight-pr

#1934 OTG - TE-11.1 and TE-11.2 tests update
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
Labels: keysight-pr

#2061 OTG: Align the OTG test TE-3.5 with ATE
  feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
Labels: keysight-pr

#2044 Changes to Gosnappi Data type refactor changes
  feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/bgp_keepalive_and_holdtimer_configuration_test.go
  feature/example/tests/topology_test/topology_test.go
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/experimental/isis/otg_tests/internal/session/attrs.go
  feature/experimental/isis/otg_tests/isis_interface_passive_test/isis_interface_passive_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/isis_metric_style_wide_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/isis_metric_style_wide_not_enabled_test.go
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go
  feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go
  feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/traceroute_packetin_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/tun_acl_dscp_test.go
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go
  feature/gribi/otg_tests/get_rpc_test/get_rpc_test.go
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
  feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
  feature/gribi/otg_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
  feature/gribi/otg_tests/weighted_balancing_test/setup_test.go
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
  feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go
  feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
  feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
  feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go
  feature/qos/otg_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
  feature/qos/otg_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
  feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
  feature/qos/otg_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
  feature/qos/otg_tests/wrr_traffic_test/wrr_traffic_test.go
  go.mod
  go.sum
  internal/attrs/attrs.go
Labels: keysight-pr

#1855 TE3.7 Added Drain Implementation Test and modified existing test.
  feature/gribi/ate_tests/base_hierarchical_nhg_update/README.md
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/README.md
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  internal/args/args.go
Labels: cisco-pr
