Repository openconfig/featureprofiles, pull requests merged in 2023-01, with the labels that each got.

#721 Adding Type as GetRequest_CONFIG in GetRequest
  feature/system/gnmi/get/tests/system_gnmi_get_test/system_gnmi_get_test.go
Labels: cisco-pr

#973 TE-3.3 increase the traffic distribution deviation
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Labels: cisco-pr

#972 TE 3.3 Order of replace operations for vrf and interface
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Labels: cisco-pr

#987 Te 3.3 3 revert uninetional change added by
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Labels: cisco-pr

#981 P4RT node name mapping for Cisco 8xxx
  feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
  go.mod
  go.sum
Labels: cisco-pr

#984 RT-5.1 modify checks for counters
  feature/interface/singleton/ate_tests/singleton_test/singleton_test.go
Labels: cisco-pr

#711 TE 3.5 fix weight validation
  feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go
Labels: cisco-pr

#990 RT-5.1 add Ia deviation IPv4(6)/Neighbor
  feature/interface/singleton/ate_tests/singleton_test/singleton_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#871 Uplift rt1.2 for route_policy under neighbor
  feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#774 P4RT-7.2 LLDP PacketOut (original PR 541)
  feature/experimental/p4rt/ate_tests/lldp_packetout_test/README.md
  feature/experimental/p4rt/ate_tests/lldp_packetout_test/lldp_packetout_test.go
  feature/experimental/p4rt/ate_tests/lldp_packetout_test/rundata_test.go
Labels: cisco-pr

#590 P4RT-7.1 PacketIn
  feature/experimental/p4rt/ate_tests/lldp_packetin_test/README.md
  feature/experimental/p4rt/ate_tests/lldp_packetin_test/lldp_packetin_test.go
  feature/experimental/p4rt/ate_tests/lldp_packetin_test/rundata_test.go
Labels: P0, cisco-pr

#991 OC 1.1: increase timeout for await call
  feature/system/tests/system_base_test/hostname_test.go
  feature/system/tests/system_base_test/time_test.go
Labels: cisco-pr

#730 RT 1.7 local_bgp_test.go , RT1.5 bgp_prefix_limit_test.go, RT1.4 bgp_graceful_restart_test.go
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
Labels: juniper-pr

#865 Fixes for P4RT-5.2
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/README.md
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: cisco-pr

#870 Uplift RT1.5 for Routerid, global address family, route-policy
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#974 RT-1.1: Enabling NetworkInstance_Protocol name and identifier configuration
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Labels: nokia-pr

#849 proposal for P4RT-2.1 Mastership test
  feature/experimental/p4rt/tests/p4rt_election/README.md
  feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
  feature/experimental/p4rt/tests/p4rt_election/rundata_test.go
Labels: nokia-pr

#872 Added tests for te11.3 and related changes
  feature/experimental/gribi/ate_tests/backup_nhg_action/README.md
  feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/ate_tests/backup_nhg_action/rundata_test.go
  internal/gribi/gribi.go
Labels: cisco-pr

#1007 Remove superfluous debug lines from singleton_test
  feature/interface/singleton/ate_tests/singleton_test/singleton_test.go
Labels: google-pr

#999 OC 1.1 increase timeout for await call
  feature/system/tests/system_base_test/hostname_test.go
  feature/system/tests/system_base_test/time_test.go
Labels: cisco-pr

#908 OTG Test - P4RT-5.2: Traceroute Packetout
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/README.md
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/packetout_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: keysight-pr

#996 RT1.3 updated route-policy under neighbor afisafi
  feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/rundata_test.go
Labels: cisco-pr

#943 RT-5.1: Singleton Interface
  feature/interface/singleton/ate_tests/singleton_test/singleton_test.go
Labels: juniper-pr

#994 BGP 1.7
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#933 OTG Test: P4RT-3.2: Google Discovery Protocol: PacketOut
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/README.md
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go
Labels: keysight-pr

#1012 TE-15.1
  feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go
  go.mod
  go.sum
Labels: cisco-pr

#815 OTG Test - RT-3.2: Protocol Dscp Rules For Vrf Selection Test
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: keysight-pr

#1015 TE-11.1: Backup NHG Single NH : Fix migration to use election id handshake in func TestIndirectBackupNexthopGroup
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
Labels: juniper-pr

#1041 OC 1.2
  feature/networkinstance/ate_tests/defaults_test/defaults_test.go
Labels: cisco-pr

#1034 uplift list_tests
  tools/list_tests.sh
Labels: nokia-pr
