Repository openconfig/featureprofiles, pull requests merged in 2023-05, with the labels that each got.

#1387 TE-13.1: Add Arista support for CoreFileCheck functionality and fix an issue with configuring parent L3 interface
  feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
Labels: arista-pr

#1496 RT-2.1 | Remove IS-IS hello padding Adaptive mode deviation
  feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1492 Remove deviation MissingCPUMfgName
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1446 Add a deviation to wait after delete link qualification for post call cleanup.
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
  internal/deviations/deviations.go
Labels: arista-pr

#1521 Cisco ntp deviation
  feature/system/ntp/tests/system_ntp_test/server_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1511 gNMI-1.4: Telemetry Inventory Test - runtime improvements
  feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: juniper-pr

#1384 some of the checks should be skipped for Arista_7280 which is Not a m…
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: arista-pr

#1510 TE-3.7: Increasing number of flows to achieve consistent loadbalancing
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: juniper-pr

#1542 gNMI-1.10: Remove missing hw port deviation
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1394 OTG Test - RT-5.4: Aggregate Forwarding Viable
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/README.md
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/metadata.textproto
Labels: keysight-pr

#1544 Arista_7280 OC component EOS has parent type Chassis
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: arista-pr, google-pr

#1476 OTG Test Updates - gnmi-1.10 and gnmi-1.11
  feature/gnmi/otg_tests/telemetry_basic_check_test/README.md
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Labels: keysight-pr

#1489 OTG RT-1.3: BGP Route Propagation (Add WatchAll)
  feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
Labels: keysight-pr

#1545 TE-11.3:Added deviation to skip traffic forwarding verification when primary path for reencap destination fails.
  feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1550 TE -13.1 /13.2 - Remove deviation
  feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1548 Additional requirements for Optics Power and Bias Current
  feature/platform/tests/optics_power_and_bias_current_test/README.md
  feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Labels: google-pr

#1551 Add disk and cpu to telemetry
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
  feature/platform/ate_tests/telemetry_inventory_test/README.md
  feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: google-pr

#1538 RT-1.7,RT-1.5,RT-1.10 | Add BGP route-policy config under AFI/SAFI by default
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/README.md
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/README.md
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/tests/local_bgp_test/README.md
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/README.md
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/bgp_keepalive_and_holdtimer_configuration_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1577 Add validation of software version
  feature/gnoi/os/tests/osinstall/osinstall_test.go
Labels: google-pr

#1579 Update NTP Test Plan & Test
  feature/system/ntp/tests/system_ntp_test/README.md
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
  feature/system/ntp/tests/system_ntp_test/server_test.go
  feature/system/ntp/tests/system_ntp_test/system_ntp_test.go
Labels: google-pr

#1568 OTG: DP-1.8: Updating the test "Two strict priority queue traffic test" to Align with ATE
  feature/qos/otg_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
Labels: keysight-pr

#1570 RT-3.1/RT-3.2: Added deviation to skip interface-ref config for unsupported NOS
  feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1647 GNMI-1.2, 1.3: Replacing ISISLevelAuthenticationNotRequired deviation with new ISISExplicitLevelAuthenticationConfig deviation
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/deviations/deviations.go
Labels: nokia-pr

#1567 OTG: DP-1.7: Updating the test "One strict priority queue traffic test" to Align with ATE
  feature/qos/otg_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
Labels: keysight-pr
