Repository openconfig/featureprofiles, pull requests merged in 2023-06, with the labels that each got.

#1653 gNMI-1.4: Adding a new deviation for unsupported telemetry path /components/component/storage
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1641 P4RT-2.1 -Remove deviation P4RTUnsetElectionIDUnsupported
  feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1633 P4RT-6.1 Performance Test
  feature/experimental/p4rt/ate_tests/performance_test/README.md
  feature/experimental/p4rt/ate_tests/performance_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/performance_test/performance_test.go
Labels: juniper-pr

#1661 OTG Tests Update - RT-5.2 and RT-5.4
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
Labels: bug, keysight-pr

#1679 gNMI-1.3,RT-1.2,RT-1.3,RT-1.4 | Changes to add RPL under BGP Peer-group AFI without deviation
  feature/bgp/addpath/ate_tests/route_propagation_test/README.md
  feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go
  feature/bgp/addpath/otg_tests/route_propagation_test/README.md
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/README.md
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  feature/bgp/policybase/ate_tests/route_installation_test/README.md
  feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
  feature/bgp/policybase/otg_tests/route_installation_test/README.md
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1720 gnmi-1.4: disable mfg-name validation for cpu component type
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: nokia-pr

#1315 te-3.1: update test coverage as per #1132
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  internal/gribi/gribi.go
Labels: nokia-pr

#1638 RT-3.2: added check for ARP resolution from OTG
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: nokia-pr

#1685 Update qos_ecn_config_test.go
  feature/qos/tests/qos_ecn_config_test/qos_ecn_config_test.go
Labels: cisco-pr

#1686 Update qos_policy_config_test.go
  feature/qos/tests/qos_policy_config_test/qos_policy_config_test.go
Labels: cisco-pr

#1687 TE-1.2: remove mac address missing deviation
  feature/experimental/interface/my_station_mac/ate_tests/my_station_mac_test/my_station_mac_test.go
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/my_station_mac_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1675 Update wrr_traffic_test.go
  feature/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
  feature/qos/otg_tests/wrr_traffic_test/wrr_traffic_test.go
Labels: cisco-pr

#1674 Update two_sp_queue_traffic_test.go
  feature/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
  feature/qos/otg_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
Labels: cisco-pr

#1673 Update one_sp_queue_traffic_test.go
  feature/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
  feature/qos/otg_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
Labels: cisco-pr

#1671 Update qos_output_queue_counters_test.go
  feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
  feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: cisco-pr

#1672 Update qos_basic_test.go
  feature/qos/ate_tests/qos_basic_test/qos_basic_test.go
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: cisco-pr

#1677 Update bursty_traffic_test.go
  feature/qos/ate_tests/bursty_traffic_test/bursty_traffic_test.go
  feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go
Labels: cisco-pr

#1676 Cisco dp 1.10 uprev
  feature/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
  feature/qos/otg_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Labels: cisco-pr

#1736 TE-3.1: Added deviation ipv6_enable_for_gribi_nh_dmac in metadata.textproto
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
Labels: juniper-pr

#1243 OTG Test Update - RT-6.1: Core LLDP TLV Population
  feature/lldp/otg_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
  feature/lldp/otg_tests/core_lldp_tlv_population_test/metadata.textproto
  internal/otgutils/print.go
Labels: keysight-pr

#1692 TE-14.1/TE-3.3/TE-3.1: Refactored the deviation for interface-ref config
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Labels: juniper-pr

#1665 gNMI-1.4: Removing deviation added in pull/1403
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1740 Te 3.1 deviation
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  internal/gribi/gribi.go
Labels: cisco-pr

#1701 gNOI-3.2: adding support for fabric component reboot
  feature/gnoi/system/tests/per_component_reboot_test/README.md
  feature/gnoi/system/tests/per_component_reboot_test/metadata.textproto
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, anCX

#1693 RT-1.12 bgp_always_compare_med
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/README.md
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
Labels: juniper-pr, anCX

#1680 ntp deviation
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
  feature/system/ntp/tests/system_ntp_test/system_ntp_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#1770 restore mac+interface-ref addNH() code in gribi.go helper
  internal/gribi/gribi.go
Labels: nokia-pr

#1779 OC-26.1: Added deviation ntp_non_default_vrf_unsupported for Juniper
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
Labels: juniper-pr

#1778 TE-3.3: Increased tolerance to avoid flakiness observed
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
Labels: juniper-pr

#1746 TE-3.1: Updating metadata.textproto with missing deviation
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
Labels: nokia-pr

#1767 gNMI-1.4:Removed TestSoftwareModule test and deviation_components_software_module_unsupported
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#1745 OTG: P4RT-6.1: Required Packet I/O rate: Performance
  feature/experimental/p4rt/otg_tests/performance_test/README.md
  feature/experimental/p4rt/otg_tests/performance_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
Labels: keysight-pr

#1775 TE-3.1_fix : gribi programming support with mac and ipaddress combination
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  internal/gribi/gribi.go
Labels: cisco-pr

#1721 RT-1.11 - BGP remove private AS
  feature/experimental/bgp/ate_tests/bgp_remove_private_as/README.md
  feature/experimental/bgp/ate_tests/bgp_remove_private_as/bgp_remove_private_as_test.go
  feature/experimental/bgp/ate_tests/bgp_remove_private_as/metadata.textproto
Labels: juniper-pr, anCX

#1810 OC-26.1: Network Time Protocol (NTP)
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
Labels: juniper-pr

#1808 RT-1.12: adding route-policy import for ebgp sessions
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
Labels: cisco-pr
