Repository openconfig/featureprofiles, pull requests merged in 2023-02, with the labels that each got.

#896 OTG Test - TE-6.2: Route Removal In Non Default VRF
  feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
  feature/gribi/otg_tests/route_removal_non_default_vrf_test/rundata_test.go
Labels: keysight-pr

#1029 RT IS-IS 2.2 Changes to IS-IS LSP Updates test
  feature/experimental/isis/ate_tests/lsp_updates_test/lsp_updates_test.go
Labels: cisco-pr

#1036 P4RT-5.2 deviation for handling ttl0 and hoplimit0 packets
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go
  feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
Labels: cisco-pr

#897 OTG Tests Updates - RT-5.2, RT-5.3, TE-14.1
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
  feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go
  topologies/kne/atedut_lag.testbed
Labels: keysight-pr

#953 fixes for isis RT 2.1
  feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/experimental/isis/ate_tests/internal/session/session.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1040 Gnoi-5.2 : add deviations for l4 protocol and fragmenation
  feature/gnoi/system/tests/traceroute_test/traceroute_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#860 gNMI-1.13_Telemetry_Optics_Power_and_Bias_Current : Added interface type configuration
  feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Labels: juniper-pr

#912 TE-2.1: gRIBI IPv4 Entry : Adding ipv6 entry for this testcase
  feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#859 TE-3.7: Base Hierarchical NHG Update : Updated Ipv6 address info for all dut ports
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: juniper-pr

#1010 TE-3.1: Base Hierarchical Route Installation - porting script changes from ATE to OTG location
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
Labels: juniper-pr

#1050 P4RT-5.1 traceroute packetin fix
  feature/experimental/p4rt/ate_tests/traceroute_packetin_test/README.md
  feature/experimental/p4rt/ate_tests/traceroute_packetin_test/packetin_test.go
  feature/experimental/p4rt/ate_tests/traceroute_packetin_test/traceroute_packetin_test.go
Labels: cisco-pr

#1033 gNOI-3.2: Updating Watch function timeout duration for interface OperStatus
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
Labels: nokia-pr

#1042 TE11.1_fix
  feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
Labels: cisco-pr

#1013 gNMI-1.8_Configuration_Metadata-only_Retrieve_and_Replace : Adding ho…
  feature/system/gnmi/metadata/tests/annotation_test/annotation_test.go
Labels: juniper-pr

#1064 Modified config of member link before configuring aggregate interface
  feature/gnmi/ate_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
Labels: juniper-pr

#792 RT 2.1 and RT 2.2 base_adjacencies_test.go , lsp_updates_test.go
  feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/ate_tests/lsp_updates_test/lsp_updates_test.go
  feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/lsp_updates_test/lsp_updates_test.go
Labels: juniper-pr

#907 OTG Test - P4RT-1.1: Base P4RT Functionality
  feature/experimental/p4rt/otg_tests/base_p4rt/README.md
  feature/experimental/p4rt/otg_tests/base_p4rt/base_p4rt_test.go
  feature/experimental/p4rt/otg_tests/base_p4rt/rundata_test.go
Labels: keysight-pr

#1045 Modify BGP keepalive and holdtime values to accommodate different vendors
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
Labels: juniper-pr

#901 OTG Test - TE-8.1: DUT Daemon Failure
  feature/experimental/gribi/otg_tests/dut_daemon_failure/README.md
  feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
  feature/experimental/gribi/otg_tests/dut_daemon_failure/rundata_test.go
Labels: keysight-pr

#1055 Added instance type configuration for DEFAULT instance
  feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: juniper-pr

#1080 added NI/PortSpeed deviations
  feature/experimental/p4rt/ate_tests/lldp_packetout_test/lldp_packetout_test.go
Labels: nokia-pr

#1056 Added vlan config for subinterface while creating subinterface and binding to network instance and added deviation to configure vlan-id for all subinterfaces
  feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: juniper-pr

#1075 OTG: Making the test P4RT-7.1 align with ATE test
  feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go
Labels: keysight-pr

#1068 Added instance type for DEFAULT instance and updated NH index to have…
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
Labels: juniper-pr

#934 OTG Test: P4RT-5.1: Traceroute: PacketIn
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/README.md
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/packetin_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/rundata_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/traceroute_packetin_test.go
Labels: keysight-pr

#1082 RT-5.2 and RT-5.3 udpated for NI/PortSpeed deviations
  feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go
  feature/interface/aggregate/ate_tests/balancing_test/balancing_test.go
Labels: nokia-pr

#1095 TE-3.6 fix test issue for creation of static route
  feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
Labels: cisco-pr

#1089 DP-1.4: Need to create forwarding groups prior to using them in a classifier
  feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: juniper-pr

#1087 DP-1.4: Handle differences in QoS queue names/numbers across vendors
  feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: juniper-pr

#1118 TE-6.2: Moving ATE protocol start after DUT NI configuration
  feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
Labels: nokia-pr

#1099 TE 3.3 prevent the traffic ratio from being rounded up
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
Labels: cisco-pr

#1117 TE-3.7: Moving Interface creation before it is attached to VRF.
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: nokia-pr

#639 gNMI-1.2: Benchmarking: Full Configuration Replace
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/README.md
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/full_configuration_replace_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/rundata_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/args/args.go
Labels: juniper-pr

#652 gNMI-1.10 - Changes for Vendor specific component names
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: cisco-pr

#1122 RT1.4 Changes
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1020 TE-1.2: My Station MAC
  feature/experimental/interface/my_station_mac/ate_tests/my_station_mac_test/README.md
  feature/experimental/interface/my_station_mac/ate_tests/my_station_mac_test/my_station_mac_test.go
  feature/experimental/interface/my_station_mac/ate_tests/my_station_mac_test/rundata_test.go
Labels: juniper-pr

#1162 Update ExplicitPortSpeed deviation
  internal/fptest/portspeed.go
Labels: nokia-pr

#1155 TE-1.1: refactor usage of ExplicitPortSpeed deviation
  feature/interface/staticarp/ate_tests/static_arp_test/static_arp_test.go
  feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
  internal/fptest/portspeed.go
Labels: nokia-pr

#1165 GNMI-1.11: Adding support for ExplicitPortSpeed & ExplicitInterfaceInDefaultVRF deviation
  feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Labels: nokia-pr

#1129 OTG RT2.1: Fix for Retrieving port name using Eth.Connection
  feature/experimental/isis/otg_tests/internal/session/session.go
Labels: keysight-pr

#675 gNOI-4.1: Add OSActivateNoReboot and OSInstallForStandbyRP deviations
  feature/gnoi/os/tests/osinstall/osinstall_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1051 Adding deviation for RT-6.1
  feature/lldp/tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1178 GNMI-1.13: Updating vendor based transceiverMAP and transceiverName
  feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Labels: nokia-pr

#1113 TE-3.7: Base Hierarchical NHG Update: ExplicitIPv6EnableForGRIBI deviation
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: juniper-pr

#1110 TE-2.1: gRIBI IPv4 Entry - Added interface type ethernetCsmacd
  feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Labels: juniper-pr

#1073 OTG: Making the test P4RT-3.2 align with ATE test
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go
Labels: keysight-pr

#1112 TE-3.2: Traffic Balancing According to Weights - Adding interface type ethernetCsmacd
  feature/gribi/otg_tests/weighted_balancing_test/setup_test.go
Labels: juniper-pr

#1166 Correct interface numbering in juniper_ixia_lag.textproto
  topologies/kne/juniper_ixia_lag.textproto
Labels: juniper-pr

#645 gNMI-1.3 Benchmarking: Drained Configuration Convergence Time
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/README.md
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_isis_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/rundata_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
Labels: juniper-pr

#1116 gNOI-5.3_Copying_Debug_Files : Adding code to killing bgp process usi…
  feature/gnoi/system/tests/copying_debug_files_test/copying_debug_files_test.go
Labels: juniper-pr

#1027 TE-13.2 route_removal_during_failover_test
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/README.md
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/rundata_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1180 OTG Test Update - DP-1.4: QoS Interface Output Queue Counters
  feature/experimental/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: keysight-pr

#1145 RT 2.1 - base_adjacencies_test.go
  feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go
  internal/check/check.go
Labels: juniper-pr
