Repository openconfig/featureprofiles, pull requests merged in 2023-07, with the labels that each got.

#1800 Update wrr_traffic_test.go
  feature/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
  feature/qos/otg_tests/wrr_traffic_test/wrr_traffic_test.go
Labels: cisco-pr

#1797 Update qos_basic_test.go
  feature/qos/ate_tests/qos_basic_test/qos_basic_test.go
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: cisco-pr

#1798 Update qos_output_queue_counters_test.go
  feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
  feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: cisco-pr

#1792 cisco-leaf-ref-changes
  feature/qos/tests/qos_policy_config_test/qos_policy_config_test.go
Labels: cisco-pr

#1794 Update bursty_traffic_test.go
  feature/qos/ate_tests/bursty_traffic_test/bursty_traffic_test.go
  feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go
Labels: cisco-pr

#1796 Update one_sp_queue_traffic_test.go
  feature/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
  feature/qos/otg_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
Labels: cisco-pr

#1799 Update two_sp_queue_traffic_test.go
  feature/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
  feature/qos/otg_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
Labels: cisco-pr

#1795 Update mixed_sp_wrr_traffic_test.go
  feature/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
  feature/qos/otg_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Labels: cisco-pr

#1814 Remove gNOI-5.2 Traceroute do_not_fragment case
  feature/gnoi/system/tests/traceroute_test/metadata.textproto
  feature/gnoi/system/tests/traceroute_test/traceroute_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1822 FP-1.1: increase timeout for linecard, skipping power off/on for non-removable components and added a new deviation
  feature/platform/tests/power_admin_down_up_test/metadata.textproto
  feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#1572 gNOI-2.1: Adding MTU config, ASIC loopback reflector mode and a new deviation
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/README.md
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#1804 P4RT-1.1: Base P4RT Functionality OTG_test
  feature/experimental/p4rt/otg_tests/base_p4rt/base_p4rt_test.go
Labels: juniper-pr

#1784 RT-1.10 : Added instance type configuration for DEFAULT instance
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/bgp_keepalive_and_holdtimer_configuration_test.go
Labels: juniper-pr

#1857 DP-1.14: Updating queue names for queue names for Juniper
  feature/qos/ate_tests/qos_basic_test/qos_basic_test.go
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: juniper-pr

#1858 OC-26.1: enable deviation for Nokia
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
Labels: nokia-pr

#1877 OTG Tests Update - Replaced local with packaged function
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_leader_election_test/base_leader_election_test.go
  feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
  feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
  feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
  feature/gribi/otg_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
  feature/gribi/otg_tests/weighted_balancing_test/setup_test.go
Labels: keysight-pr

#1859 gnmi-1.4: enable backplane-facing-capacity unsup. deviation for Nokia
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: nokia-pr

#1870 P4RT: Removing deviation explicit_p4rt_node_component for Nokia.
  feature/experimental/p4rt/ate_tests/base_p4rt/metadata.textproto
  feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetin_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetout_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/lldp_packetin_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/lldp_packetout_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/p4rt_daemon_failure_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/performance_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/traceroute_packetin_test/metadata.textproto
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/metadata.textproto
  feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
  feature/experimental/p4rt/otg_tests/base_p4rt/metadata.textproto
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/lldp_packetin_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/lldp_packetout_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/p4rt_daemon_failure_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/performance_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/traceroute_packetin_test/metadata.textproto
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/metadata.textproto
  feature/experimental/p4rt/tests/p4rt_election/metadata.textproto
Labels: nokia-pr

#1912 Fixing KNE textproto for Nokia
  cloudbuild/virtual.sh
  topologies/kne/nokia/srlinux/dut.textproto
  topologies/kne/nokia/srlinux/dutate.textproto
  topologies/kne/nokia/srlinux/dutate_lag.textproto
  topologies/kne/nokia/srlinux/dutdut.textproto
  topologies/kne/nokia/srlinux/topology.textproto
Labels: nokia-pr

#1879 gnsi binding
  go.mod
  go.sum
  internal/deviations/byexceptions.go
  topologies/binding/binding.go
  topologies/binding/gnsi.go
Labels: cisco-pr

#1919 add mtls
  go.mod
  go.sum
  topologies/binding/options.go
  topologies/proto/binding.proto
  topologies/proto/binding/binding.pb.go
Labels: cisco-pr

#1741 OTG Test Update TE-15.1 - Added skipIdempotentDelete
  feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
Labels: keysight-pr

#1852 FP-1.1: Adding deviation and Skipping check for Empty fabric component
  feature/platform/tests/power_admin_down_up_test/metadata.textproto
  feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
Labels: nokia-pr

#1926 p4rt-2.2: fix writeReadTableEntry()
  feature/experimental/p4rt/tests/metadata_validation_test/metadata_validation_test.go
Labels: nokia-pr

#1817 RT-1.19: BGP 2-byte and 4-byte ASN support
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/README.md
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/metadata.textproto
Labels: juniper-pr, anCX

#1806 Update qos_ecn_config_test.go
  feature/qos/tests/qos_ecn_config_test/qos_ecn_config_test.go
Labels: cisco-pr

#1840 RT-1.12 : BGP always compare MED OTG test
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/README.md
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
Labels: juniper-pr, anCX

#1819 RT-1.14 BGP Long-Lived Graceful Restart
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/README.md
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
Labels: juniper-pr, anCX

#1816 Remove sw version deviation for cisco
  feature/gnmi/ate_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnoi/os/tests/osinstall/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#1860 Initial commit for TC RT-1_20
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/README.md
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/bgp_2byte_4byte_asn_policy_test.go
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
Labels: juniper-pr, anCX

#677 Factory Reset
  feature/gnoi/factory_reset/tests/factory_reset_test/README.md
  feature/gnoi/factory_reset/tests/factory_reset_test/factory_reset_test.go
  feature/gnoi/factory_reset/tests/factory_reset_test/metadata.textproto
Labels: cisco-pr

#1847 RT-2.10: IS-IS change LSP lifetime
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/README.md
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/isis_change_lsp_lifetime_test.go
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/metadata.textproto
Labels: juniper-pr, anCX

#1875 GNMI-1.10: Removing manufacturer name validation for CPU
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: nokia-pr

#1702 p4rt-6.1: small fixes
  feature/experimental/p4rt/ate_tests/performance_test/performance_test.go
Labels: nokia-pr

#1954 P4RT6.1: porting PR#1702 changes to OTG
  feature/experimental/p4rt/otg_tests/performance_test/performance_test.go
Labels: nokia-pr
