Repository openconfig/featureprofiles, pull requests merged in 2023-11, with the labels that each got.

#2340 Nokia KNE fixes for OC-1.1
  README.md
  cloudbuild/virtual.sh
  topologies/kne/nokia/srlinux/config.cfg
  topologies/kne/nokia/srlinux/dut.textproto
  topologies/kne/nokia/srlinux/dutate.textproto
  topologies/kne/nokia/srlinux/dutate_lag.textproto
  topologies/kne/nokia/srlinux/dutdut.textproto
  topologies/kne/nokia/srlinux/dutdutate.textproto
  topologies/kne/nokia/srlinux/topology.textproto
Labels: nokia-pr

#2331 DP1.3: Added deviations for CISCO
  feature/qos/tests/qos_ecn_config_test/metadata.textproto
  feature/qos/tests/qos_ecn_config_test/qos_ecn_config_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2234 gNOI-3.2: Skip test for no removable fabric card and line cards found
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
  internal/args/args.go
Labels: juniper-pr

#2336 gnmi-1.10: add default num of queues for nokia
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: nokia-pr

#2335 gnmi-1.10 & gnmi-1.11: remove an unused deviation for nokia
  feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/metadata.textproto
Labels: nokia-pr

#2344 Removing deviation route_policy_under_afi_unsupported for Nokia
  feature/bgp/addpath/otg_tests/route_propagation_test/metadata.textproto
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/metadata.textproto
  feature/bgp/policybase/otg_tests/route_installation_test/metadata.textproto
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/metadata.textproto
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/metadata.textproto
  feature/bgp/tests/local_bgp_test/metadata.textproto
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/tests/full_configuration_replace_test/metadata.textproto
Labels: nokia-pr

#2303 Bgp asn policy update
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/bgp_2byte_4byte_asn_policy_test.go
Labels: juniper-pr, anCX

#2194 Adding deviation for enable leaf under isis level
  feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/bgp_tcp_mss_path_mtu_test.go
  feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/metadata.textproto
  feature/experimental/isis/otg_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/isis_interface_level_passive_test.go
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/isis_metric_style_wide_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/isis_metric_style_wide_not_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
  feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/internal/setup/setup.go
  feature/experimental/system/gnmi/benchmarking/tests/full_configuration_replace_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2284 DP-1.3 - Adding required interface ref config
  feature/qos/tests/qos_ecn_config_test/metadata.textproto
  feature/qos/tests/qos_ecn_config_test/qos_ecn_config_test.go
Labels: juniper-pr

#2248 RT2.10 Correcting random failures
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/isis_change_lsp_lifetime_test.go
Labels: juniper-pr, anCX

#2314 Removing InterfaceRefConfigUnsupported deviation for Policy-forwarding
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/metadata.textproto
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/metadata.textproto
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/otg_tests/gribi_scaling/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2356 gNOI-3.2: Adding wait time to avoid false failures
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
Labels: juniper-pr

#2304 RT-5.6 interface_loopback_aggregate_test.go : Added deviation
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2351 RT-5.4: Configure LACP on the interface only when LAG type is LACP
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: juniper-pr

#2169 OTG Test Update - TE-6.1 Stats check for continuous traffic
  feature/gribi/otg_tests/route_removal_via_flush_test/route_removal_via_flush_test.go
  internal/otgutils/actions.go
Labels: keysight-pr

#2206 RT-1.2, RT-1.10 , RT-1.12, RT-1.3, RT-1.7, RT-1.5 : Removed deviation
  feature/bgp/addpath/otg_tests/route_propagation_test/metadata.textproto
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/metadata.textproto
  feature/bgp/policybase/otg_tests/route_installation_test/metadata.textproto
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/metadata.textproto
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/metadata.textproto
  feature/bgp/tests/local_bgp_test/metadata.textproto
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/metadata.textproto
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
Labels: juniper-pr

#2341 Changes for plq test
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2345 FP-1.1: Remove skip_fabric_card_power_admin deviation
  feature/platform/tests/power_admin_down_up_test/metadata.textproto
  feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2152 gNMI-1.14 TestPlan: OpenConfig metadata consistency during large config push
  feature/system/gnmi/metadata/tests/lagre_set_consistency_test/README.md
Labels: enhancement, P0

#2363 p4rt-3.1 & p4rt-7.1: add missing check on metadata length
  feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go
  feature/experimental/p4rt/otg_tests/lldp_packetin_test/lldp_packetin_test.go
Labels: nokia-pr

#2421 Make collecting of dutinfo to be controlled by a flag
  internal/rundata/rundata.go
Labels: cisco-pr

#2424 P4RT-1.2: Updated the port name verification with p1.Name() instead of dutPort1.Name
  feature/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
Labels: juniper-pr

#2219 RT-1.5 / refactor: exception for explicit prefix limit *received*
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/metadata.textproto
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr
