Repository openconfig/featureprofiles, pull requests merged in 2023-10, with the labels that each got.

#2166 explicit_gribi_under_network_instance deviation removal from all gribi tests
  feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
  feature/experimental/backup_nhg/ate_tests/backup_nhg_test/metadata.textproto
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/metadata.textproto
  feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/ate_tests/backup_nhg_action/metadata.textproto
  feature/experimental/gribi/ate_tests/route_addition_during_failover_test/metadata.textproto
  feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/metadata.textproto
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/metadata.textproto
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/metadata.textproto
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/metadata.textproto
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/gribi/ate_tests/ack_in_presence_other_routes/metadata.textproto
  feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/ate_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  feature/gribi/ate_tests/backup_nhg_multiple_nh_test/metadata.textproto
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/ate_tests/gribi_scaling/metadata.textproto
  feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go
  feature/gribi/ate_tests/gribigo_compliance_test/metadata.textproto
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
  feature/gribi/ate_tests/route_removal_non_default_vrf_test/metadata.textproto
  feature/gribi/ate_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
  feature/gribi/otg_tests/ack_in_presence_other_routes/metadata.textproto
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/otg_tests/gribi_scaling/metadata.textproto
  feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
  feature/gribi/otg_tests/gribigo_compliance_test/metadata.textproto
  feature/gribi/otg_tests/route_removal_non_default_vrf_test/metadata.textproto
  feature/gribi/otg_tests/route_removal_non_default_vrf_test/route_removal_non_default_vrf_test.go
Labels: nokia-pr

#2049 OTG: RT-1.12_BGP always compare MED (Align the test with ATE test) & added MED verification on OTG
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/README.md
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
Labels: keysight-pr

#2092 Add helper to generate svid using rsa and ecdsa certs
  go.sum
  internal/security/svid/svid.go
  internal/security/svid/svid_test.go
  internal/security/svid/testdata/ecdsa/ca-ecdsa-cert.pem
  internal/security/svid/testdata/ecdsa/ca-ecdsa-key.pem
  internal/security/svid/testdata/rsa/ca-rsa-cert.pem
  internal/security/svid/testdata/rsa/ca-rsa-key.pem
Labels: cisco-pr

#2186 TE-11.2:Updated script to use flow metrics for traffic verification
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
Labels: juniper-pr

#2198 OTG Test Update - RT-5.4 Fix the ATE destination device name
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: keysight-pr

#2182 RT2.6,RT2.8,RT2.9-modified scripts to use session.go from the internal folder
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/isis_metric_style_wide_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/isis_metric_style_wide_not_enabled_test.go
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
Labels: juniper-pr, anCX

#1940 OTG TE-1.1 Update - Egress tracking added
  feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
  internal/otgutils/arp.go
Labels: keysight-pr

#2048 TE-9.1 : FIB FAILURE DUE TO HARDWARE RESOURCE EXHAUST
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/README.md
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/fib_failed_due_to_hw_res_exhaust_test.go
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2214 gNOI-2.1: Add support for Nokia to PLQ test
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
Labels: nokia-pr

#2209 GNMI-1.13: Enabling deviation transceiver_thresholds_unsupported
  feature/platform/tests/optics_power_and_bias_current_test/metadata.textproto
Labels: nokia-pr

#2022 DP-1.3: Adding test support for Nokia
  feature/qos/tests/qos_ecn_config_test/metadata.textproto
  feature/qos/tests/qos_ecn_config_test/qos_ecn_config_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2075 MissingIsisInterfaceAfiSafiEnable deviation remove
  feature/experimental/isis/ate_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/ate_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/experimental/isis/ate_tests/lsp_updates_test/metadata.textproto
  feature/experimental/isis/otg_tests/base_adjacencies_test/metadata.textproto
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
  feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
  feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/metadata.textproto
  feature/experimental/system/gnmi/benchmarking/ate_tests/full_configuration_replace_test/metadata.textproto
Labels: cisco-pr

#2119 OTG : RT-2.1 Set origin to external
  feature/experimental/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
Labels: keysight-pr

#1845 OC-26.1 TestPlan: Extend NTP test to cover source IP
  feature/system/ntp/feature.textproto
  feature/system/ntp/tests/system_ntp_test/README.md
Labels: documentation, enhancement, P1, WBB Catalog Feature audit

#1871 TR-6.1 TestPlan: System logging remote syslog
  feature/system/logging/remote_syslog/feature.textproto
  feature/system/logging/remote_syslog/otg_tests/README.md
  feature/system/logging/remote_syslog/otg_tests/metadata.textproto
Labels: documentation, enhancement, P1, WBB Catalog Feature audit

#2204 RT-1.14: BGP Long-Lived Graceful Restart : Deviation to use native cli for BGP LLGR Disable
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, anCX

#2042 TUN-1.4 Interface based IPv6 GRE Encapsulation
  feature/experimental/tunnel/otg_tests/tunnel_interface_based_ipv6_gre_encapsulation_test/README.md
  feature/experimental/tunnel/otg_tests/tunnel_interface_based_ipv6_gre_encapsulation_test/metadata.textproto
  feature/experimental/tunnel/otg_tests/tunnel_interface_based_ipv6_gre_encapsulation_test/tunnel_interface_based_ipv6_gre_encapsulation_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, anCX

#2087 Remove missing_interface_physical_channel deviation
  feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2243 gNOI-2.1: Packet-based Link-Qual: add interface oper-state validation
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/README.md
Labels: enhancement

#2181 feat: mtu-1.3: large ip packet transmission
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/README.md
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/large_ip_packet_transmission_test.go
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/metadata.textproto
Labels: nokia-pr, anCX

#2286 rt-5.6 update
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/README.md
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2052 add isis drain test
  feature/experimental/isis/otg_tests/isis_drain_test/README.md
  feature/experimental/isis/otg_tests/isis_drain_test/isis_drain_test.go
  feature/experimental/isis/otg_tests/isis_drain_test/metadata.textproto
Labels: nokia-pr

#2296 add core validator to feature profiles
  go.mod
  go.sum
  internal/core/core.go
  internal/core/core_test.go
  topologies/binding/new.go
Labels: enhancement, google-pr

#2233 RT-5.2: Cleanup LACP and LAG configs to avoid potential conflicts in config
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
Labels: juniper-pr
