Repository openconfig/featureprofiles, pull requests merged in 2023-12, with the labels that each got.

#2377 gNOI-4.1: Adding config push verification post OS upgrade
  feature/gnoi/os/tests/osinstall/osinstall_test.go
Labels: juniper-pr, new-requirement-pr

#2404 Added new ip address blocks
  CONTRIBUTING.md
  tools/check_ip_addresses.pl
Labels: juniper-pr

#2425 Adding default accept term for as-path regex policy
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/bgp_2byte_4byte_asn_policy_test.go
Labels: juniper-pr

#2143 RT-1.1 | Remove SkipBGPTestPasswordMismatch deviation
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2195 OTG: RT1.5 Updated the test not to restart BGP for each test case
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
Labels: keysight-pr

#2118 OTG: RT 2.2 Align the test with ATE
  feature/experimental/isis/otg_tests/lsp_updates_test/lsp_updates_test.go
Labels: keysight-pr

#2316 Modify for P4RT-5.2
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: juniper-pr

#2403 RT-5.1: Singleton Interface
  feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
Labels: juniper-pr

#2379 RT-1.23: BGP AFI SAFI OC DEFAULTS : Added new subtest
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/README.md
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2474 Fix metadata.textproto changed from PR 2461
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/metadata.textproto
Labels: nokia-pr

#2277 refactor: gnmi-1.12 nokia deviation for native yang instead of cli in multi origin
  feature/system/gnmi/cliorigin/tests/mixed_oc_cli_origin_support_test/metadata.textproto
  feature/system/gnmi/cliorigin/tests/mixed_oc_cli_origin_support_test/mixed_oc_cli_origin_support_test.go
  proto/metadata_go_proto/metadata.pb.go
Labels: P0, nokia-pr

#2352 RT-7 : bgp_default_policies_test.go
  feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
  feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, new-requirement-pr

#2460 Changed testbed file for gNMI-1.14
  feature/system/gnmi/metadata/tests/large_set_consistency_test/metadata.textproto
Labels: nokia-pr

#2459 Add delay for BGP update to propagate gNMI-1.3
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
Labels: nokia-pr

#2415 TE-2.2: moved static route under deviation condition
  feature/gribi/otg_tests/ipv4_entry_with_aggregate_ports_test/ipv4_entry_with_aggregate_ports_test.go
Labels: P0, nokia-pr

#2298 P4RT-1.2: fix bug in subscribeOnChangeInterfaceName
  feature/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
Labels: cisco-pr

#2492 Updated the test case id number for IPv6 ND RA disable.
  testregistry.textproto
Labels: juniper-pr

#2401 GNMI-1.11: Adding tolerance for incoming/outgoing packet delta equivalence check
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
Labels: P0, nokia-pr

#2333 GNMI-1.15: Adding deviation static_route_next_hop_interface_ref_unsupported
  feature/system/gnmi/set/tests/gnmi_set_test/gnmi_set_test.go
  feature/system/gnmi/set/tests/gnmi_set_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2420 Adding vendor support for RT-1.19
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/metadata.textproto
Labels: nokia-pr

#2495 GNMI-1.13: Adding Temperature/Instant check from Sensor
  feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
Labels: P0, nokia-pr

#2328 gNMI-1.15: gnmi_set_test.go : Added deviation
  feature/system/gnmi/set/tests/gnmi_set_test/README.md
  feature/system/gnmi/set/tests/gnmi_set_test/gnmi_set_test.go
  feature/system/gnmi/set/tests/gnmi_set_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr
