Repository openconfig/featureprofiles, pull requests merged in 2023-09, with the labels that each got.

#2062 OTG: Align the OTG test TE11.3 with ATE
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
Labels: keysight-pr

#2051 p4rt-2.2: remove deviation for nokia
  feature/experimental/p4rt/tests/metadata_validation_test/metadata.textproto
Labels: nokia-pr

#2064 OTG: Align the OTG test RT_1.2 with ATE
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
Labels: keysight-pr

#1963 Do not overwrite grpc.dialoptions when they are set by the caller
  topologies/binding/options.go
Labels: cisco-pr

#2083 OTG RT5.4: Add FEC related config
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: keysight-pr

#2076 DP-1.14 TestPlan: QoS DSCP transparecny with ECN
  feature/qos/ecn/otg_tests/DSCP-transparency/README.md
Labels: enhancement, P0

#1862 Code commit for Health-1.1: Generic Health Check
  feature/experimental/system/health/tests/system_generic_health_check/README.md
  feature/experimental/system/health/tests/system_generic_health_check/metadata.textproto
  feature/experimental/system/health/tests/system_generic_health_check/system_generic_health_check_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, anCX

#1964 RT-2.6: IS-IS Hello-Padding enabled at interface level
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/README.md
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/isis_interface_hello_padding_enable_test.go
  feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
Labels: juniper-pr, anCX

#2007 OTG: Unique name for device not to overlap with Lag name
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
  feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go
  internal/deviations/byexceptions.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: keysight-pr

#2065 Align OTG test RT5.1 with ATE test
  feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
Labels: keysight-pr

#2026 DP-1.14: Adding test support for Nokia
  feature/qos/ate_tests/qos_basic_test/metadata.textproto
  feature/qos/ate_tests/qos_basic_test/qos_basic_test.go
  feature/qos/otg_tests/qos_basic_test/metadata.textproto
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: nokia-pr

#2105 dutdutate testbed
  cloudbuild/virtual.sh
  internal/fptest/runtests.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
  topologies/dutdutate.testbed
  topologies/kne/arista/ceos/dutdutate.textproto
  topologies/kne/cisco/8000e/dutdutate.textproto
  topologies/kne/cisco/xrd/dutdutate.textproto
  topologies/kne/juniper/cptx/dutdutate.textproto
  topologies/kne/nokia/srlinux/dutdutate.textproto
  topologies/kne/openconfig/lemming/dutdutate.textproto
Labels: juniper-pr, anCX

#2071 FP-1.1 deviation removed
  feature/platform/tests/power_admin_down_up_test/metadata.textproto
  feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2121 Update RT-1.20 to RT-1.24
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/README.md
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
Labels: juniper-pr, anCX

#2001 DP-1.2: Adding test support for Nokia
  feature/qos/tests/qos_policy_config_test/metadata.textproto
  feature/qos/tests/qos_policy_config_test/qos_policy_config_test.go
Labels: nokia-pr

#2023 DP-1.4: Adding test support for Nokia
  feature/qos/otg_tests/qos_output_queue_counters_test/metadata.textproto
  feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
Labels: nokia-pr

#2123 DP-1.14: Fixing error in forwarding group config
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: nokia-pr

#1635 TE-1.1:adding case insensitive check for mac
  feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
Labels: nokia-pr

#2122 gNMI-1.13: New deviation for transceiver thresholds
  feature/platform/tests/optics_power_and_bias_current_test/metadata.textproto
  feature/platform/tests/optics_power_and_bias_current_test/optics_power_and_bias_current_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2082 RT-1.23 BGP AFI-SAFI OC Defaults
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/README.md
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
Labels: juniper-pr, anCX

#2088 fixed the tun1.9 subnet issue
  feature/experimental/tunnel/otg_tests/tunnel_acl_based_test/tun_acl_dscp_test.go
Labels: juniper-pr, anCX

#1853 RT-1.11 - BGP remove private AS  - OTG test
  feature/experimental/bgp/otg_tests/bgp_remove_private_as/README.md
  feature/experimental/bgp/otg_tests/bgp_remove_private_as/bgp_remove_private_as_test.go
  feature/experimental/bgp/otg_tests/bgp_remove_private_as/metadata.textproto
Labels: juniper-pr, anCX

#2109 OTG: TE_11.1 Re-enable "Disable ATE port-2" test
  feature/experimental/backup_nhg/otg_tests/backup_nhg_test/backup_nhg_test.go
Labels: keysight-pr

#2079 Rt 5.6 fix
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#1976 RT-2.8: IS-IS Passive is enabled at the area level
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/README.md
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/isis_interface_level_passive_test.go
  feature/experimental/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
Labels: juniper-pr, anCX

#1885 RT-5.5 TestPlan: Interface hold-time up, down test specification
  feature/interface/holdtime/feature.textproto
  feature/interface/holdtime/otg_tests/holdtime_test/README.md
  feature/interface/holdtime/otg_tests/holdtime_test/metadata.textproto
Labels: enhancement, P1, WBB Catalog Feature audit

#1843 RT-5.6 TestPlan: Specification for disable IPv6 ND Router Advertisement
  feature/interface/ipv6_ND/feature.textproto
  feature/interface/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/README.md
  feature/interface/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/metadata.textproto
  topologies/proto/binding/binding.pb.go
Labels: documentation, enhancement, P1, WBB Catalog Feature audit

#2039 RT-2.10: IS-IS change LSP lifetime
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/README.md
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/isis_change_lsp_lifetime_test.go
  feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto
Labels: juniper-pr, anCX

#2066 Configure NI name whenever configuring type
  feature/bgp/addpath/ate_tests/route_propagation_test/route_propagation_test.go
  feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
  feature/experimental/bgp/ate_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/bgp/otg_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/internal/session/session.go
  feature/experimental/policy/policy_vrf_selection/ate_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/ate_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/gribi/ate_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/ate_tests/get_rpc_test/get_rpc_test.go
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/get_rpc_test/get_rpc_test.go
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
  feature/networkinstance/ate_tests/defaults_test/defaults_test.go
  feature/networkinstance/otg_tests/defaults_test/defaults_test.go
  internal/fptest/networkinstance.go
Labels: cisco-pr

#1642 RT-5.4 TestPlan: Updated test Plan to capture intended behaviour of Forwarding viable
  feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/README.md
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/README.md
Labels: enhancement, P1

#1657 RT-5.7 TestPlan: Aggregate All Not Viable - README for new test
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/README.md
Labels: enhancement, P1

#1910 RT-1.21: BGP TCP MSS and PMTUD
  feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/README.md
  feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/bgp_tcp_mss_path_mtu_test.go
  feature/experimental/bgp/otg_tests/bgp_tcp_mss_path_mtu/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, anCX

#1968 gNMI-1.10 TestPlan: Fabric redundancy
  feature/platform/fabric/feature.textproto
  feature/platform/fabric/otg_tests/fabric_redundancy_test/README.md
  feature/platform/fabric/otg_tests/fabric_redundancy_test/metadata.textproto
Labels: enhancement, P2, WBB Catalog Feature audit

#2058 gNMI-1.15 TestPlan: Conroller Card redundancy test plan (README.md)
  feature/platform/controllercard/feature.textproto
  feature/platform/controllercard/tests/README.md
  feature/platform/controllercard/tests/metadata.textproto
Labels: enhancement, P1, WBB Catalog Feature audit

#2172 TE-3.7_otg_ate_fix
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: cisco-pr

#2024 DP-1.10: Adding test support for Nokia
  feature/qos/otg_tests/mixed_sp_wrr_traffic_test/metadata.textproto
  feature/qos/otg_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2185 Using correct global AS variable for bgp_2byte_4byte_asn_test
  feature/experimental/bgp/ate_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
Labels: juniper-pr, anCX

#2126 P4RT-5.2: add subtests for all metadata combinations
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/README.md
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/packetout_test.go
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: cisco-pr
