Repository openconfig/featureprofiles, pull requests merged in 2023-04, with the labels that each got.

#1360 Update qos_policy_config_test.go
  feature/qos/ate_tests/qos_policy_config_test/qos_policy_config_test.go
Labels: cisco-pr

#1333 RT-1.4: adding bgp permit all policy
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
Labels: nokia-pr

#1373 TE-2.1 | Add a deviation for MAC override case
  feature/gribi/ate_tests/ipv4_entry_test/ipv4_entry_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#763 OTG Test - RT-3.1: Policy based VRF selection
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/README.md
  feature/experimental/policy/policy_vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
Labels: keysight-pr

#1182 OTG Test - TE-1.2: My Station MAC
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/README.md
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/metadata.textproto
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/my_station_mac_test.go
Labels: keysight-pr

#1192 Update README for P4RT-2.1
  feature/experimental/p4rt/tests/p4rt_election/README.md
Labels: google-pr

#1277 gNMI-1.4: refactor test to use type rather than regex, add deviations and args
  feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/args/args.go
Labels: cisco-pr

#1356 TE-14.1 - Fixing nexthop address for instance vrf3
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
Labels: juniper-pr

#1376 RT-5.4: Enabling deviation and updating config order
  feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: nokia-pr

#1362 RT 1.7 adding deviation for last notification error
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1391 Update wrr_traffic_test.go
  feature/experimental/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
Labels: cisco-pr

#1181 Te11.2 update
  feature/gribi/ate_tests/backup_nhg_multiple_nh_test/README.md
  feature/gribi/ate_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  internal/gribi/gribi.go
Labels: cisco-pr

#1368 GNMI-1.3: Updating configuration for routing-policy under peer-group and interface to default-NI
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_isis_test.go
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
Labels: nokia-pr

#1386 OC-1.1: Added deviation for skip telemetry check for hostname and domain-name
  feature/system/tests/system_base_test/hostname_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1334 te-13.1: update readme according to the test code
  feature/experimental/gribi/ate_tests/route_addition_during_failover_test/README.md
Labels: nokia-pr

#1335 TE-11.3 implemented changes as per PR 1158
  feature/experimental/gribi/ate_tests/backup_nhg_action/README.md
  feature/experimental/gribi/ate_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  internal/gribi/gribi.go
Labels: nokia-pr

#1389 RT-1.4 Adding Native SRL ACL compatibility
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  internal/deviations/deviations.go
Labels: nokia-pr

#1204 gNMI-1.4: Telemetry: Inventory - Removed fabricChip from the list of components; added vendor specific deviations
  feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1399 Fix P4RT-5.2: Traceroute Packetout test
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/packetout_test.go
  feature/experimental/p4rt/ate_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: arista-pr

#1375 P4RT-2.1 -Update deviation for UnsetElectionID with P4RTUnsetElectionIDUnsupported
  feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1350 DP-1.7: One strict priority queue traffic test - Updated changes required for scheduler input parameters, vendor specific queue-id and ExplicitInterfaceRefDefinition deviation
  feature/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1388 p4rt-2.1: fix usage of wantfail flag
  feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
Labels: nokia-pr

#1404 DP-1.14 : QoS basic test - Adding required QoS config
  feature/experimental/qos/ate_tests/qos_basic_test/qos_basic_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1366 GNMI-1.2: Adding deviation for authentication and updating ISIS configuration
  feature/experimental/system/gnmi/benchmarking/ate_tests/internal/setup/setup.go
  internal/deviations/deviations.go
Labels: nokia-pr

#1392 RT-1.2: OTG - Setting DefaultNetworkInstance on the device
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
Labels: juniper-pr

#1238 TE-14.1: fix vrf assignment
  feature/gribi/ate_tests/gribi_scaling/README.md
  feature/gribi/ate_tests/gribi_scaling/gribi_scaling_test.go
  feature/gribi/otg_tests/gribi_scaling/README.md
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Labels: nokia-pr

#1406 TE-11.1 : Updated AFT verification for device that returns the recursively resolved nexthop
  feature/experimental/backup_nhg/ate_tests/backup_nhg_test/backup_nhg_test.go
Labels: juniper-pr

#1395 DP-1.4: QoS Interface Output Queue Counters - Removing SchedulerInputParamsUnsupported deviation and adding scheduler weight limit deviation
  feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1407 gNMI-1.11: Adding a new deviation for IPv6 discarded packet stats support
  feature/gnmi/ate_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1403 gNMI-1.4: Added deviation for fanOperStatusUnsupported
  feature/platform/ate_tests/telemetry_inventory_test/telemetry_inventory_test.go
  internal/deviations/deviations.go
Labels: juniper-pr

#1369 Add Arista support for coreFileCheck functionality in TE-13.2
  feature/experimental/gribi/ate_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
Labels: arista-pr

#1422 RT-2.1, RT-2.2 | Enable IS-IS wide metric-style by default without the deviation
  feature/experimental/isis/ate_tests/internal/session/session.go
  feature/experimental/isis/otg_tests/internal/session/session.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1380 DP-1.9 - WRR traffic test - Adding required vendor specific queue name change and interface-ref definition
  feature/experimental/qos/ate_tests/wrr_traffic_test/wrr_traffic_test.go
Labels: juniper-pr

#1378 DP-1.8 - Two strict priority queue traffic test - Adding required vendor specific queue name change and interface-ref definition
  feature/qos/ate_tests/two_sp_queue_traffic_test/two_sp_queue_traffic_test.go
Labels: juniper-pr

#1379 DP-1.10 - Mixed strict priority and WRR traffic test - Adding required vendor specific queue name change and interface-ref definition
  feature/qos/ate_tests/mixed_sp_wrr_traffic_test/mixed_sp_wrr_traffic_test.go
Labels: juniper-pr

#1423 Remove deviation InterfaceOperStatus
  feature/interface/aggregate/ate_tests/aggregate_test/aggregate_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1390 RT-5.4: Update ATE config order to start LACP before IP
  feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: nokia-pr

#1432 adding missing README update for OTG from PR-1335
  feature/experimental/gribi/otg_tests/backup_nhg_action/README.md
Labels: nokia-pr

#1434 TE-3.1: remove test for gribi delete mode
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/ate_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
Labels: cisco-pr

#1436 TE-4.2: remove grib delete mode from test
  feature/gribi/ate_tests/persistence_mode_test/README.md
  feature/gribi/ate_tests/persistence_mode_test/persistence_mode_test.go
  feature/gribi/otg_tests/persistence_mode_test/README.md
  feature/gribi/otg_tests/persistence_mode_test/persistence_mode_test.go
Labels: cisco-pr

#1428 P4RT: update P4RTNodesByPort to support breakout ports
  feature/experimental/p4rt/internal/p4rtutils/p4rtutils.go
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: cisco-pr

#1197 OTG Test - DP-1.9: WRR traffic test
  feature/experimental/qos/otg_tests/wrr_traffic_test/README.md
  feature/experimental/qos/otg_tests/wrr_traffic_test/metadata.textproto
  feature/experimental/qos/otg_tests/wrr_traffic_test/wrr_traffic_test.go
Labels: keysight-pr

#1372 Fix RT-1.7: Local BGP Test for Arista with necessary deviations
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
Labels: arista-pr

#1265 OTG Test - DP-1.11: Bursty traffic test
  feature/qos/otg_tests/bursty_traffic_test/README.md
  feature/qos/otg_tests/bursty_traffic_test/bursty_traffic_test.go
  feature/qos/otg_tests/bursty_traffic_test/metadata.textproto
Labels: keysight-pr

#1439 TE-3.5: Remove gribi delete mode
  feature/gribi/ate_tests/ordering_ack_test/README.md
  feature/gribi/ate_tests/ordering_ack_test/ordering_ack_test.go
  feature/gribi/otg_tests/ordering_ack_test/README.md
  feature/gribi/otg_tests/ordering_ack_test/ordering_ack_test.go
Labels: cisco-pr

#1443 Remove GRIBIPreserveOnly deviation
  internal/deviations/deviations.go
Labels: cisco-pr

#1424 gNMI-1.10: update sw version check according to the new README
  feature/gnmi/ate_tests/telemetry_basic_check_test/README.md
  feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  feature/gnmi/otg_tests/telemetry_basic_check_test/README.md
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  internal/components/components.go
  internal/deviations/deviations.go
Labels: nokia-pr

#1431 Removing deviation for MissingBgpNeighborStatePeerGroup
  feature/bgp/tests/local_bgp_test/local_bgp_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1447 fixed static route NH index
  feature/gribi/otg_tests/ack_in_presence_other_routes/route_ack_test.go
Labels: nokia-pr

#1444 TE-3.3-uprev: Opened PR to address CLA check failing for PR 1417
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1255 TE-3.7: update with changes from #1135
  feature/gribi/ate_tests/base_hierarchical_nhg_update/README.md
  feature/gribi/ate_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/README.md
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: nokia-pr

#1437 RT-3.2: OTG: Changed the ATE source MAC from "01:00:02:01:01:01" to "00:12:01:00:00:01"
  feature/experimental/policy/policy_vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: juniper-pr

#1430 TE-14.1 - OTG: Fixed nexthop address for instance vrf3
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Labels: juniper-pr

#1456 Fix revive errors
  internal/gribi/gribi.go
  internal/otgutils/arp.go
  tools/validate_paths.go
  topologies/binding/binding.go
  topologies/binding/cli.go
  topologies/binding/options.go
Labels: google-pr

#843 OTG Test Update - TE 11.2 Loss Pct fix
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/README.md
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
Labels: keysight-pr

#1349 OTG Test - TE-13.1: gRIBI route ADD during Failover
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/README.md
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/metadata.textproto
  feature/experimental/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
Labels: keysight-pr

#1266 OTG Test - TE-13.2: gRIBI route DELETE during Failover
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/README.md
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/metadata.textproto
  feature/experimental/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
Labels: keysight-pr

#1336 OTG Test - DP-1.14: QoS basic test
  feature/experimental/qos/otg_tests/qos_basic_test/README.md
  feature/experimental/qos/otg_tests/qos_basic_test/metadata.textproto
  feature/experimental/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: keysight-pr

#1463 Changes to RT-1.4 & remove deviation
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  internal/deviations/deviations.go
Labels: cisco-pr

#1457 Delete feature/experimental/qos/ate_tests/wrr_traffic_test directory
  feature/experimental/qos/ate_tests/wrr_traffic_test/README.md
Labels: google-pr

#1462 RT-1.5 BGP prefixlimit | Fixes for overlimit case & remove deviation
  feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  internal/deviations/deviations.go
Labels: cisco-pr
