Repository openconfig/featureprofiles, pull requests merged in 2024-01, with the labels that each got.

#2498 RT-7 fix loopback config
  feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
Labels: P0, nokia-pr

#2462 gNOI-4.1 Adding Nokia deviation
  feature/gnoi/os/tests/osinstall/metadata.textproto
  feature/gnoi/os/tests/osinstall/osinstall_test.go
Labels: P0, nokia-pr

#2504 RT-1.1: Updating await timeout for BGP session with correct password
  feature/experimental/bgp/ate_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
Labels: nokia-pr

#2487 added test requirement for BGP multipath ECMP
  feature/bgp/multipath/feature.textproto
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/README.md
  testregistry.textproto
Labels: enhancement

#2522 TE-15.1: Adding flag to skip ipv6 compliance cases
  feature/gribi/otg_tests/gribigo_compliance_test/gribigo_compliance_test.go
  go.mod
  go.sum
Labels: nokia-pr

#2538 SFLOW-1.1: Updating metadata with static_protocol_name deviation
  feature/sflow/otg_tests/sflow_base_test/metadata.textproto
Labels: nokia-pr

#2546 Fix GRPC timeout for OTG
  topologies/binding/binding.go
Labels: nokia-pr

#2397 Enhance debug capabilities for gNOI-3.1
  feature/gnoi/system/tests/complete_chassis_reboot/complete_chassis_reboot_test.go
Labels: nokia-pr

#2540 Fix authz policy
  feature/security/gnsi/authz/tests/authz/testdata/policy.json
Labels: nokia-pr

#2544 Vendor deviation fix for gnoi-4.1
  feature/gnoi/os/tests/osinstall/osinstall_test.go
Labels: nokia-pr

#2549 Adding PKCS8 to LoadKeyPair()
  internal/security/svid/svid.go
Labels: nokia-pr

#2520 Static route redistribution to IS-IS readme
  feature/isis/static-route_isis_redistribution/README.md
  testregistry.textproto
Labels: enhancement, P0

#2557 Fix for system_base_test
  feature/system/tests/system_base_test/g_protocol_test.go
  topologies/binding/options.go
Labels: nokia-pr

#2485 RT-9: Disable IPv6 ND Router Advertisement
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/README.md
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/disable_ipv6_nd_ra_test.go
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, new-requirement-pr

#2511 RT-1.5 bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#1352 OTG Test - RT-1.1: Base BGP Session Parameters
  feature/experimental/bgp/otg_tests/base_bgp_session_parameters/README.md
  feature/experimental/bgp/otg_tests/base_bgp_session_parameters/base_bgp_session_parameters_test.go
  feature/experimental/bgp/otg_tests/base_bgp_session_parameters/metadata.textproto
Labels: keysight-pr

#2297 OTG Test - Gnmi-1.5 Telemetry: Port Speed Test
  feature/gnmi/otg_tests/telemetry_port_speed_test/README.md
  feature/gnmi/otg_tests/telemetry_port_speed_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_port_speed_test/telemetry_port_speed_test.go
Labels: keysight-pr

#2457 add methods and options for ipv6 in internal gribi.go to be used for dcgate tests
  internal/gribi/gribi.go
Labels: cisco-pr

#2576 Adding vendor Deviations
  feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
  feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/metadata.textproto
Labels: nokia-pr

#2577 OTG TE11.3 Update Flow tracking bits from 12 to 10 & removed deviation ATEPortLinkStateOperationsUnsupported
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
Labels: keysight-pr

#2591 Adding 8port testbed
  cloudbuild/virtual.sh
  internal/fptest/runtests.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
  topologies/atedut_8.binding
  topologies/atedut_8.testbed
Labels: juniper-pr
