Repository openconfig/featureprofiles, pull requests merged in 2024-11, with the labels that each got.

#3561 Added defer function to cleanup fib table
  feature/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/fib_failed_due_to_hw_res_exhaust_test.go
Labels: nokia-pr

#3432 Rt 1.54 bgp_override_as_path_split_horizon_test.go
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/README.md
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/metadata.textproto
  internal/cfgplugins/bgp.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3573 [gNMI-1.14] prune device config before push
  feature/system/gnmi/metadata/tests/large_set_consistency_test/README.md
  feature/system/gnmi/metadata/tests/large_set_consistency_test/large_set_consistency_test.go
  feature/system/gnmi/metadata/tests/large_set_consistency_test/metadata.textproto
  feature/system/gnmi/set/tests/gnmi_set_test/gnmi_set_test.go
  internal/fptest/config.go
Labels: cisco-pr

#3522 Add export policy test cases to link bandwidth test
  feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
Labels: google-pr

#3470 Cisco logical channels
  feature/platform/transceiver/tests/zr_logical_channels_test/metadata.textproto
  feature/platform/transceiver/tests/zr_logical_channels_test/zr_logical_channels_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3487 Cisco zr pm test
  feature/platform/transceiver/tests/zr_pm_test/metadata.textproto
  feature/platform/transceiver/tests/zr_pm_test/zr_pm_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3608 updated metadata for nokia with deviations
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
Labels: nokia-pr

#3359 Modifications to RT 1.28-BGP to IS-IS redistribution
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/bgp_isis_redistribution_test.go
Labels: juniper-pr
