Repository openconfig/featureprofiles, pull requests merged in 2024-12, with the labels that each got.

#3513 RT-2.12 Fixed with deviations & minor changes
  feature/isis/otg_tests/static_route_isis_redistribution/metadata.textproto
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3371 RT-7.5: Remove deviation bgp_conditions_match_community_set_unsupported
  feature/bgp/policybase/otg_tests/link_bandwidth_test/metadata.textproto
Labels: P1

#3572 RT-1.52: BGP multipath UCMP support with Link Bandwidth Community changes incorporated
  feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/bgp_multipath_wecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/metadata.textproto
Labels: P1, nokia-pr

#3424 RT-5.7: Fix ISIS issues
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
Labels: cisco-pr

#3625 RT-1.51| remove skip_setting_allow_multiple_as deviation in metadata file
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/metadata.textproto
Labels: cisco-pr

#3626 RT-1.54 bgp_override_as_path_split_horizon_test.go
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
Labels: juniper-pr

#3624 DP-1.14: Adding deviation for no zero suppression
  feature/qos/otg_tests/qos_basic_test/metadata.textproto
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3630 TE-16.1 TTL deviation removed
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
Labels: cisco-pr

#3571 RT-1.51: BGP multipath ECMP changes incorporated
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/bgp_multipath_ecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/metadata.textproto
Labels: P1, nokia-pr

#3593 RT-7.8: BGP Policy Match Standard Community and Add Community Import/Export Policy changes incorporated
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Labels: P1, nokia-pr

#3537 DP-1.2: Fixing validation of non strict priority scheduler case for Juniper
  feature/qos/tests/qos_policy_config_test/qos_policy_config_test.go
Labels: juniper-pr

#3615 gnmi-1.4 | change to use state path for power-admin-state leaf
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: cisco-pr

#3650 MGT-1 : management_ha_test.go
  feature/system/management/otg_tests/management_ha_test/management_ha_test.go
Labels: juniper-pr

#3618 deviation for RT-2.9
  feature/isis/otg_tests/isis_metric_style_wide_enabled_test/isis_metric_style_wide_enabled_test.go
  feature/isis/otg_tests/isis_metric_style_wide_enabled_test/metadata.textproto
Labels: cisco-pr

#3612 Update RT-5.6 to change link down on port1 instead of all ports
  feature/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
Labels: keysight-pr

#3614 RT-5.8 monitor interface stats before proceeding with test
  feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
Labels: cisco-pr

#2767 RT-1.32 : actions_MED_LocPref_prepend_flow_control_test.go
  feature/bgp/policybase/otg_tests/actions_med_localpref_prepend_flow_control/actions_MED_LocPref_prepend_flow_control_test.go
  feature/bgp/policybase/otg_tests/actions_med_localpref_prepend_flow_control/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3597 RT-5.9 deviation
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/metadata.textproto
Labels: cisco-pr

#2815 gNMI-1.27-updating deviation,isis_level_enabled
  feature/gnmi/subscribe/tests/gnmi_sample_mode_test/metadata.textproto
Labels: juniper-pr

#3456 RT-5.8: IPv6 Link Local : Changes to await for interface up check after replace config for OTG
  feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
Labels: juniper-pr

#3560 GNMI-1.18: Skipping check for empty integrated-circuit and removing deviations
  feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/metadata.textproto
  feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/sampled_backplane_capacity_counters_test.go
Labels: nokia-pr

#3551 [gNOI-6.1] fix remote file path for cisco
  feature/gnoi/factory_reset/tests/factory_reset_test/factory_reset_test.go
Labels: cisco-pr

#3567 RT-1.28: Fixed script with added deviations
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/bgp_isis_redistribution_test.go
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/metadata.textproto
  internal/deviations/deviations.go
  internal/fptest/tableconnection.go
  proto/metadata.proto
Labels: P1, nokia-pr

#3467 OTG: RT 1.26
  feature/staticroute/otg_tests/basic_static_route_support_test/basic_static_route_support_test.go
Labels: keysight-pr
