Repository openconfig/featureprofiles, pull requests merged in 2024-08, with the labels that each got.

#3259 fixes mgt-1 : Management HA solution test
  feature/system/management/otg_tests/management_ha_test/management_ha_test.go
  feature/system/management/otg_tests/management_ha_test/metadata.textproto
  internal/cfgplugins/bgp.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3263 RT-1.34 admin_distance_test changes incorporated
  feature/bgp/admin_distance/otg_tests/admin_distance_test/admin_distance_test.go
  feature/bgp/admin_distance/otg_tests/admin_distance_test/metadata.textproto
Labels: nokia-pr

#3163 fix static to bgp redistribution test
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
Labels: google-pr

#3251 P4RT 5.2 OTG fix
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: nokia-pr

#2916 TE-14.2 : encap_decap_scale_test.go
  feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
  feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
Labels: juniper-pr

#3367 RT-7.5: changes for Cisco within existing deviation
  feature/experimental/bgp/otg_tests/link_bandwidth_test/link_bandwidth_test.go
Labels: cisco-pr

#3311 RT-7.11: Remove deviation skip_prefix_set_mode
  feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
Labels: arista-pr

#3305 Added missing deviation and resource name for Nokia
  feature/platform/integrated_circuit/otg_tests/utilization_test/metadata.textproto
  feature/platform/integrated_circuit/otg_tests/utilization_test/utilization_test.go
  internal/components/components.go
Labels: nokia-pr

#3351 Fixed gNMI1.27
  feature/gnmi/subscribe/tests/gnmi_sample_mode_test/README.md
  feature/gnmi/subscribe/tests/gnmi_sample_mode_test/gnmi_sample_mode_test.go
  feature/gnmi/subscribe/tests/gnmi_sample_mode_test/metadata.textproto
Labels: nokia-pr

#3327 RT-1.53 fix
  feature/experimental/policy/otg_tests/prefix_set_test/metadata.textproto
  feature/experimental/policy/otg_tests/prefix_set_test/prefix_set_test.go
Labels: nokia-pr

#2974 GNMI-1.18: Adding power-admin configuration skip for empty fabric slot
  feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/sampled_backplane_capacity_counters_test.go
Labels: nokia-pr

#3304 corrected deviation usage and isis await timeout
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/metadata.textproto
Labels: nokia-pr

#3369 RT-6.1 Fix
  feature/lldp/ate_tests/core_lldp_tlv_population_test/README.md
  feature/lldp/ate_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
  feature/lldp/otg_tests/core_lldp_tlv_population_test/README.md
  feature/lldp/otg_tests/core_lldp_tlv_population_test/core_lldp_tlv_population_test.go
Labels: nokia-pr

#3374 gnmi-1.4: fix deviations for nokia
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
Labels: nokia-pr

#3255 TE-8.2 fix telemetry fetching for standby
  feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
Labels: nokia-pr

#2293 RT-2.7 Support for Nokia
  feature/experimental/isis/otg_tests/isis_interface_passive_test/README.md
  feature/experimental/isis/otg_tests/isis_interface_passive_test/isis_interface_passive_test.go
  feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
Labels: nokia-pr

#3110 RT-1.33 : bgp_prefix_set_test.go
  feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
Labels: juniper-pr

#3386 fixed the failure that was introduced by PR-3376
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
  feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
  feature/experimental/policy/otg_tests/prefix_set_test/prefix_set_test.go
  feature/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
  internal/gnoi/gnoi.go
Labels: nokia-pr

#3379 RT-7.8: Add bgp_community_set_refs deviation for Nokia
  feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Labels: nokia-pr

#3247 Removed `explicit_gribi_under_network_instance`/`ExplicitGRIBIUnderN…
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/metadata.textproto
  feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
  feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
  internal/deviations/deviations.go
  internal/fptest/networkinstance.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3396 RT-1.53 - fix process name
  internal/gnoi/gnoi.go
Labels: nokia-pr

#3345 RT-7.1: Removed deviation default_import_export_policy
  feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
Labels: juniper-pr

#2922 RT-1.30: Added deviation bgp_rib_oc_path_unsupported and updated script to delete the policy applied in bgp
  feature/bgp/policybase/otg_tests/nested_policies/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
Labels: juniper-pr

#2935 Deviation:gNMI-1.18 backplane_facing_capacity_unsupported removal
  feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/metadata.textproto
  feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/sampled_backplane_capacity_counters_test.go
Labels: juniper-pr

#3366 RT-1.29 chained_policies_test.go
  feature/bgp/policybase/otg_tests/aspath_and_community_test/metadata.textproto
  feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
  feature/bgp/policybase/otg_tests/chained_policies_test/metadata.textproto
  feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
  feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
  feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
  feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3405 Add deviation for IPv6 Router Advertisement Interval configuration
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/disable_ipv6_nd_ra_test.go
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: google-pr

#3406 Add deviation for Decap NH with NextHopNetworkInstance
  feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
  feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: google-pr
