Repository openconfig/featureprofiles, pull requests merged in 2024-04, with the labels that each got.

#2827 RT-1.28, RT-1.30: Added peer-group for BGP peer and deviation for ISIS enabled
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/bgp_isis_redistribution_test.go
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
Labels: juniper-pr

#2802 TE-2.2 | Adding static arp config after interface config
  feature/gribi/otg_tests/ipv4_entry_with_aggregate_ports_test/ipv4_entry_with_aggregate_ports_test.go
Labels: cisco-pr

#2808 gNMI-1.4 | change parent type validation to use lookup
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: cisco-pr

#2641 SFLOW-1: Configure default network instance
  feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go
Labels: juniper-pr

#2900 RT-1.27: Static route to BGP redistribution
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/README.md
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
  testregistry.textproto
Labels: nokia-pr, new-requirement-pr

#2850 RT-7.8: BGP Community Match Action
  feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr, new-requirement-pr

#2772 OTG Test - TE-3.31: Hierarchical weight resolution with PBF
  feature/gribi/otg_tests/hierarchical_weight_resolution_pbf_test/README.md
  feature/gribi/otg_tests/hierarchical_weight_resolution_pbf_test/hierarchical_weight_resolution_pbf_test.go
  feature/gribi/otg_tests/hierarchical_weight_resolution_pbf_test/metadata.textproto
Labels: keysight-pr

#2885 TE-16.1 Basic Encap Test - fix for using l2 rules and sequenceID
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
Labels: cisco-pr

#2877 Authz fixes
  feature/security/gnsi/authz/tests/authz/authz1_4_test.go
  internal/security/gnxi/rpcexec.go
Labels: nokia-pr

#2855 System-1: System testing: Updates to g_protocol_test.go
  feature/system/tests/system_base_test/g_protocol_test.go
Labels: juniper-pr
