Repository openconfig/featureprofiles, pull requests merged in 2024-05, with the labels that each got.

#2898 MGT-1 Add vendor changes
  feature/system/management/otg_tests/management_ha_test/management_ha_test.go
  feature/system/management/otg_tests/management_ha_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2928 RT-1.33: Fixing value for deviation flag
  feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
  feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
Labels: nokia-pr

#2843 Rt2.12 static route redistribution
  feature/isis/otg_tests/static_route_isis_redistribution/README.md
  feature/isis/otg_tests/static_route_isis_redistribution/metadata.textproto
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: cisco-pr, new-requirement-pr

#2963 RT-2.2 | Remove isis_interface_level1_disable_required deviation
  feature/experimental/isis/otg_tests/lsp_updates_test/metadata.textproto
Labels: cisco-pr

#2915 Rt 1.26 git issue fix
  feature/staticroute/otg_tests/basic_static_route_support_test/basic_static_route_support_test.go
  feature/staticroute/otg_tests/basic_static_route_support_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2929 gNMI-1.14 enhancements
  feature/system/gnmi/metadata/tests/large_set_consistency_test/large_set_consistency_test.go
Labels: nokia-pr

#2927 RT-7.1: BGP default-policies updates
  feature/bgp/policybase/otg_tests/default_policies_test/bgp_default_policies_test.go
  feature/bgp/policybase/otg_tests/default_policies_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2998 RT-1.33 changes
  feature/bgp/policybase/otg_tests/prefix_set_test/README.md
  feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
  feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
  internal/helpers/helpers.go
Labels: cisco-pr

#2989 RT-7.2 | Changes and adding deviation
  feature/bgp/policybase/otg_tests/community_test/README.md
  feature/bgp/policybase/otg_tests/community_test/community_test.go
  feature/bgp/policybase/otg_tests/community_test/metadata.textproto
  internal/cfgplugins/bgp.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2887 TE-17.1 | Add deviations & changes
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/README.md
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
  feature/gribi/otg_tests/basic_encap_test/README.md
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  internal/attrs/attrs.go
Labels: cisco-pr

#2889 TE-16.2 Encap Frr Test - fix for using l2 rules and sequenceID
  feature/gribi/otg_tests/encap_frr/encap_frr_test.go
  feature/gribi/otg_tests/encap_frr/metadata.textproto
Labels: cisco-pr
