Repository openconfig/featureprofiles, pull requests merged in 2024-07, with the labels that each got.

#3102 P4RT-5.2 : added ARP wait on OTG
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/README.md
  feature/experimental/p4rt/otg_tests/traceroute_packetout_test/traceroute_packetout_test.go
Labels: juniper-pr

#3100 TE-14.1 : gribi_scaling_test.go
  feature/gribi/otg_tests/gribi_scaling/gribi_scaling_test.go
Labels: juniper-pr

#2835 Updates to MTU-1.3: MTU-1.3: Large IP Packet Transmission
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/large_ip_packet_transmission_test.go
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/metadata.textproto
Labels: juniper-pr

#3134 TE-14.2 encap decap scale fixes
  feature/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
  feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2792 Updating flow count and traffic duration
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
Labels: juniper-pr

#3246 RT-5.10: IPv6 Link Local generated by SLAAC
  feature/interface/ip/ipv6_slaac_link_local/otg_tests/ipv6_slaac_link_local_test/metadata.textproto
Labels: juniper-pr

#3033 TE-8.2: Added stop traffic before getting the traffic flow statistics
  feature/gribi/otg_tests/supervisor_failure_test/README.md
  feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
Labels: juniper-pr

#3133 Removal of `explicit_interface_ref_definition` deviation
  feature/gribi/ate_tests/hierarchical_weight_resolution_pbf_test/metadata.textproto
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/README.md
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  feature/gribi/otg_tests/encap_decap_scale/metadata.textproto
  feature/gribi/otg_tests/gribi_scaling/metadata.textproto
  feature/gribi/otg_tests/hierarchical_weight_resolution_pbf_test/metadata.textproto
  feature/gribi/otg_tests/hierarchical_weight_resolution_test/README.md
  feature/gribi/otg_tests/hierarchical_weight_resolution_test/metadata.textproto
Labels: nokia-pr

#2739 Modifications to RT1.26 basic_static_route_support_test.go
  feature/staticroute/otg_tests/basic_static_route_support_test/basic_static_route_support_test.go
  feature/staticroute/otg_tests/basic_static_route_support_test/metadata.textproto
Labels: juniper-pr

#3045 OTG_MTU_1.3: Change the test to pick Destination MAC based on ARP
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/large_ip_packet_transmission_test.go
Labels: keysight-pr

#3309 Add skip_bgp_send_community_type deviation
  feature/experimental/bgp/otg_tests/link_bandwidth_test/metadata.textproto
Labels: arista-pr

#3159 Removed `explicit_p4rt_node_component`/`ExplicitP4RTNodeComponent` deviation
  feature/experimental/p4rt/README.md
  feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
  internal/args/args.go
  internal/deviations/deviations.go
  internal/p4rtutils/p4rtutils.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3101 gNOI-6.1 refactor proposal
  feature/gnoi/factory_reset/tests/factory_reset_test/README.md
  feature/gnoi/factory_reset/tests/factory_reset_test/factory_reset_test.go
  feature/gnoi/factory_reset/tests/factory_reset_test/metadata.textproto
Labels: nokia-pr

#2795 TE-3.7 : base_hierarchical_nhg_update_test
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: juniper-pr

#3329 RT-5.10 Fix
  feature/interface/ip/ipv6_slaac_link_local/otg_tests/ipv6_slaac_link_local_test/ipv6_slaac_link_local_test.go
  feature/interface/ip/ipv6_slaac_link_local/otg_tests/ipv6_slaac_link_local_test/metadata.textproto
Labels: nokia-pr

#3253 Move mpls static lsp test to mpls feature
  feature/mpls/otg_tests/static_lsp/README.md
Labels: google-pr

#3341 gNMI-1.4 deviation addition
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
  feature/platform/tests/telemetry_inventory_test/telemetry_inventory_test.go
Labels: nokia-pr
