Repository openconfig/featureprofiles, pull requests merged in 2024-06, with the labels that each got.

#2842 RT-5.9: Disable IPv6 ND Router Advertisment
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/README.md
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/disable_ipv6_nd_ra_test.go
Labels: juniper-pr

#3052 TE-1.2 : Added wait for arp util func
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/README.md
  feature/experimental/interface/my_station_mac/otg_tests/my_station_mac_test/my_station_mac_test.go
Labels: juniper-pr

#3025 Adding changes and deviations for rt-7.3
  feature/bgp/policybase/otg_tests/aspath_test/README.md
  feature/bgp/policybase/otg_tests/aspath_test/aspath_test.go
  feature/bgp/policybase/otg_tests/aspath_test/metadata.textproto
Labels: cisco-pr

#2547 RT-1.51: BGP multipath ECMP and RT-1.52 bgp_multipath_wecmp_test.go : Added deviation
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/README.md
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/bgp_multipath_ecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/metadata.textproto
  feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/README.md
  feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/bgp_multipath_wecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_wecmp_lbw_community_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2588 default static route test
  feature/staticroute/tests/static_route_test/README.md
  feature/staticroute/tests/static_route_test/metadata.textproto
  feature/staticroute/tests/static_route_test/static_route_test.go
Labels: cisco-pr, anCX

#3015 Added changes for RT5.6 as to set loopback mode to TERMINAL mode under deviation
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/README.md
  feature/experimental/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go
Labels: cisco-pr

#3060 OC-26.1 | remove deviation and fix verification
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
  feature/system/ntp/tests/system_ntp_test/system_ntp_test.go
Labels: cisco-pr

#3041 RT-1.28 | Changes and adding deviations
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/README.md
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/bgp_isis_redistribution_test.go
  feature/bgp/bgp_isis_redistribution/otg_tests/bgp_isis_redistribution_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2853 gnmi-1.15 gnmi_set_test.go
  feature/system/gnmi/set/tests/gnmi_set_test/README.md
  feature/system/gnmi/set/tests/gnmi_set_test/metadata.textproto
Labels: juniper-pr

#3119 MTU-1.3: Large IP Packet Transmi… Added omit_l2_mtu: true deviation
  feature/mtu/largeippacket/otg_tests/large_ip_packet_transmission/metadata.textproto
Labels: nokia-pr

#2952 removal of set_native_acl deviation
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/README.md
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/bgp_graceful_restart_test.go
  feature/bgp/gracefulrestart/ate_tests/bgp_graceful_restart_test/metadata.textproto
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/README.md
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
  feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/README.md
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2911 gnmi-1.13: Optics Power And Bias Current Test Deviation removal
  feature/platform/tests/optics_power_and_bias_current_test/metadata.textproto
Labels: juniper-pr

#2962 TE-2.1, TE-3.1, TE-3.7 | Configure secondary IPv4 address with type leaf
  feature/gribi/otg_tests/base_hierarchical_nhg_update/README.md
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/ipv4_entry_test/README.md
  feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Labels: cisco-pr

#3057 RT-7.2: Enabling required deviation in metadata file
  feature/bgp/policybase/otg_tests/community_test/metadata.textproto
Labels: nokia-pr

#3022 RT-1.10 Enabling PrefixLimitReceived deviation
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/README.md
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/bgp_keepalive_and_holdtimer_configuration_test.go
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/metadata.textproto
Labels: nokia-pr

#3126 gNMI-1.4 Removed `backplane_facing_capacity_unsupported` deviation
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
Labels: nokia-pr

#2925 Deviations: gNMI-1.4: storage_component_unsupported,backplane_facing_capacity_unsupported removal
  feature/platform/tests/telemetry_inventory_test/metadata.textproto
Labels: juniper-pr

#2897 gNMI-1.2:Removed deviation route_policy_under_afi_unsupported
  feature/experimental/system/gnmi/benchmarking/tests/full_configuration_replace_test/README.md
  feature/experimental/system/gnmi/benchmarking/tests/full_configuration_replace_test/metadata.textproto
Labels: juniper-pr

#3070 adding changes to rt-2.13
  feature/isis/otg_tests/weighted_ecmp_test/metadata.textproto
  feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2923 OC-26.1: Network Time Protocol (NTP): Deviation:ntp_non_default_vrf_unsupported removal
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
Labels: juniper-pr
