Repository openconfig/featureprofiles, pull requests merged in 2024-02, with the labels that each got.

#2565 TE-3.1 Base Hierarchical Route Installation
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/README.md
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
Labels: juniper-pr, new-requirement-pr

#2592 RT-2.12: Updating config order
  feature/experimental/isis/otg_tests/isis_drain_test/isis_drain_test.go
Labels: nokia-pr

#2590 TE-3:7: make sure ni key 'name' is configured
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: cisco-pr

#2643 Adding Deviation to skip test with PBF action as decap/encap vrf
  feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
  feature/experimental/gribi/otg_tests/backup_nhg_action/metadata.textproto
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/hierarchical_weight_resolution_test.go
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/backup_nhg_multiple_nh_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#2551 gNMI-1.10: fix key leafref violations
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: cisco-pr

#2622 RT-5.1 change from in-discards to use in-errors for drop
  feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
Labels: cisco-pr

#2339 OTG Test - RT-1.19: BGP 2-Byte and 4-Byte ASN support
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn/README.md
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn/bgp_2byte_4byte_asn_test.go
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn/metadata.textproto
Labels: keysight-pr

#2539 Updating ip addresses list
  CONTRIBUTING.md
  tools/check_ip_addresses.pl
Labels: juniper-pr

#2519 TE-17.1 : vrf_policy_driven_te_test.go
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/README.md
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
  feature/experimental/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr, new-requirement-pr

#2548 TE-11.3,RT-1.10: configure default NI name
  feature/bgp/timers/otg_tests/bgp_keepalive_and_holdtimer_configuration_test/bgp_keepalive_and_holdtimer_configuration_test.go
Labels: cisco-pr

#2638 refactor concurrency analysis gNMI-1.14
  feature/system/gnmi/metadata/tests/large_set_consistency_test/large_set_consistency_test.go
Labels: nokia-pr

#2640 updated scale number and removed traffic check for failed route due to OTG issue
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/fib_failed_due_to_hw_res_exhaust_test.go
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/metadata.textproto
Labels: nokia-pr

#2673 TE-16.2: encap_frr
  feature/gribi/otg_tests/encap_frr/README.md
  feature/gribi/otg_tests/encap_frr/encap_frr_test.go
  feature/gribi/otg_tests/encap_frr/metadata.textproto
Labels: juniper-pr, new-requirement-pr

#2670 TE-14.2 gribi encap and decap scale
  feature/experimental/gribi/otg_tests/encap_decap_scale/README.md
  feature/experimental/gribi/otg_tests/encap_decap_scale/encap_decap_scale_test.go
  feature/experimental/gribi/otg_tests/encap_decap_scale/metadata.textproto
  internal/args/args.go
Labels: juniper-pr, new-requirement-pr

#2426 OTG Test - RT-1.24: BGP 2-Byte and 4-Byte ASN support with policy
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/README.md
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/bgp_2byte_4byte_asn_policy_test.go
  feature/experimental/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/metadata.textproto
Labels: keysight-pr

#2742 Fix KNE ACL configs pushed
  topologies/kne/nokia/srlinux/config.cfg
Labels: nokia-pr

#2456 TE-16.1: basic encap test
  feature/gribi/otg_tests/basic_encap_test/README.md
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2698 TE-2.2 | Add static protocol leafref key values in config container
  feature/gribi/otg_tests/ipv4_entry_with_aggregate_ports_test/ipv4_entry_with_aggregate_ports_test.go
Labels: cisco-pr
