Repository openconfig/featureprofiles, pull requests merged in 2024-03, with the labels that each got.

#2664 RT-5.2 fix for case-insensitive check for partnerId/systemId
  feature/interface/aggregate/otg_tests/aggregate_test/aggregate_test.go
Labels: nokia-pr

#2593 GNMI-1.11: Removing subinterface_packet_counters_missing deviation for Nokia
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/metadata.textproto
Labels: nokia-pr

#2644 SFLOW-1: static-route configuration need static protocol configuration.
  internal/cfgplugins/staticroute.go
Labels: nokia-pr

#1405 OTG: gNMI-1.3: Benchmarking: Drained Configuration Convergence Time
  feature/experimental/system/gnmi/benchmarking/internal/setup/setup.go
  feature/experimental/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/README.md
  feature/experimental/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/experimental/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_isis_test.go
  feature/experimental/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/metadata.textproto
Labels: keysight-pr

#2760 RT-1.29: Added deviation to skip BGP rib verification
  feature/bgp/policybase/otg_tests/chained_policies_test/README.md
  feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
  feature/bgp/policybase/otg_tests/chained_policies_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#2730 Adding a new test - BGP Nested_Policies_Test
  feature/bgp/policybase/otg_tests/nested_policies/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
Labels: new-requirement-pr

#2575 Adding deviation ISISLevelEnabled to RT2.12 isis_drain_test.go
  feature/experimental/isis/otg_tests/isis_drain_test/isis_drain_test.go
  feature/experimental/isis/otg_tests/isis_drain_test/metadata.textproto
Labels: juniper-pr

#2718 RT-1.33 : BGP Policy with prefix-set matching
  feature/bgp/policybase/otg_tests/prefix_set_test/bgp_prefix_set_test.go
  feature/bgp/policybase/otg_tests/prefix_set_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr, new-requirement-pr

#2648 [TE-11.21, TE-3.1, TE-3.7, TE-11.31, TE-3.31] Adding deviations for new subtest for PolicyW
  feature/experimental/gribi/otg_tests/backup_nhg_action/metadata.textproto
  feature/experimental/gribi/otg_tests/backup_nhg_action_pbf/metadata.textproto
  feature/gribi/ate_tests/hierarchical_weight_resolution_pbf_test/metadata.textproto
  feature/gribi/ate_tests/hierarchical_weight_resolution_test/metadata.textproto
  feature/gribi/otg_tests/backup_ngp_multiple_nh_pbf_test/metadata.textproto
  feature/gribi/otg_tests/backup_nhg_multiple_nh_test/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  internal/deviations/deviations.go
  internal/vrfpolicy/vrfpolicy.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2809 Migrate kne configs to grpc_server
  topologies/kne/nokia/srlinux/config.cfg
Labels: nokia-pr

#2658 RT-5.5: Interface hold-time
  feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go
  feature/interface/holdtime/otg_tests/holdtime_test/metadata.textproto
Labels: cisco-pr, anCX

#2617 gNOI-2.1 packet link qualification deviations
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/metadata.textproto
  feature/gnoi/packet_link_qualification/tests/packet_link_qualification_test/packet_link_qualification_test.go
  internal/deviations/deviations.go
  internal/vrfpolicy/vrfpolicy.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#2794 updated p4rt and gribi process names
  feature/experimental/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
  feature/p4rt/otg_tests/p4rt_daemon_failure_test/p4rt_daemon_failure_test.go
Labels: nokia-pr
