Repository openconfig/featureprofiles, pull requests merged in 2024-10, with the labels that each got.

#2805 [gNMI-1.11, RT-5.1/3] - add InterfaceCountersUpdateDelayed deviation for CISCO
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_interface_packet_counters_test/telemetry_interface_packet_counters_test.go
  feature/interface/aggregate/otg_tests/balancing_test/README.md
  feature/interface/aggregate/otg_tests/balancing_test/balancing_test.go
  feature/interface/aggregate/otg_tests/balancing_test/metadata.textproto
  feature/interface/singleton/otg_tests/singleton_test/README.md
  feature/interface/singleton/otg_tests/singleton_test/metadata.textproto
  feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3497 RT-14.2: Added mandatory instance-type config for default network-instance
  feature/gribi/otg_tests/gribi_route_test/gribi_route_test.go
Labels: juniper-pr

#3484 RT-1.51 bgp_multipath_ecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/bgp_multipath_ecmp_test.go
Labels: juniper-pr

#3397 RT-1.55: bgp_session_mode_configuration_test.go
  feature/bgp/bgp_session_mode/otg_tests/bgp_session_mode_configuration_test/README.md
  feature/bgp/bgp_session_mode/otg_tests/bgp_session_mode_configuration_test/bgp_session_mode_configuration_test.go
  feature/bgp/bgp_session_mode/otg_tests/bgp_session_mode_configuration_test/metadata.textproto
Labels: juniper-pr

#3326 healthz parameters for cisco
  feature/gnoi/system/tests/chassis_reboot_status_and_cancel_test/chassis_reboot_status_and_cancel_test.go
  feature/gnoi/system/tests/copying_debug_files_test/copying_debug_files_test.go
  feature/gnoi/system/tests/copying_debug_files_test/metadata.textproto
  feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go
  feature/gnoi/system/tests/supervisor_switchover_test/supervisor_switchover_test.go
  internal/components/components.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3058 Transceiver13: Changes to zr_low_power_mode test
  feature/platform/transceiver/tests/zr_low_power_mode_test/zr_low_power_mode_test.go
Labels: juniper-pr

#3523 adding waitForARP to fix flakiness
  feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
Labels: nokia-pr

#3258 OC-1.2 : default_tests.go
  feature/networkinstance/otg_tests/defaults_test/defaults_test.go
Labels: juniper-pr

#3301 TE-16.3: Updated script to program with non-existing tunnel destination as per README.
  feature/gribi/otg_tests/encap_frr_with_reencap_vrf_test/encap_frr_with_reencap_vrf_test.go
Labels: juniper-pr

#3534 fix BGP multipath ECMP test
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/bgp_multipath_ecmp_test.go
  feature/bgp/multipath/otg_tests/bgp_multipath_ecmp_test/metadata.textproto
Labels: google-pr

#3354 Credentialz-1
  feature/security/gnsi/credentialz/tests/README.md
  feature/security/gnsi/credentialz/tests/password_console_login/README.md
  feature/security/gnsi/credentialz/tests/password_console_login/metadata.textproto
  feature/security/gnsi/credentialz/tests/password_console_login/password_console_login_test.go
  internal/security/credz/credz.go
Labels: nokia-pr, new-requirement-pr

#3390 Accountz-2.1
  feature/security/gnsi/acctz/README.md
  feature/security/gnsi/acctz/tests/record_subscribe_partial/README.md
  feature/security/gnsi/acctz/tests/record_subscribe_partial/metadata.textproto
  feature/security/gnsi/acctz/tests/record_subscribe_partial/record_subscribe_partial_test.go
  internal/security/acctz/acctz.go
Labels: nokia-pr, new-requirement-pr

#3393 Accountz-4.2
  feature/security/gnsi/acctz/README.md
  feature/security/gnsi/acctz/tests/record_payload_truncation/README.md
  feature/security/gnsi/acctz/tests/record_payload_truncation/metadata.textproto
  feature/security/gnsi/acctz/tests/record_payload_truncation/record_payload_truncation_test.go
Labels: nokia-pr, new-requirement-pr

#3389 Accountz-1.1
  feature/security/gnsi/acctz/README.md
  feature/security/gnsi/acctz/tests/record_subscribe_full/README.md
  feature/security/gnsi/acctz/tests/record_subscribe_full/metadata.textproto
  feature/security/gnsi/acctz/tests/record_subscribe_full/record_subscribe_full_test.go
Labels: nokia-pr, new-requirement-pr

#3392 Accountz-4.1
  feature/security/gnsi/acctz/README.md
  feature/security/gnsi/acctz/tests/record_history_truncation/README.md
  feature/security/gnsi/acctz/tests/record_history_truncation/metadata.textproto
  feature/security/gnsi/acctz/tests/record_history_truncation/record_history_truncation_test.go
Labels: nokia-pr, new-requirement-pr

#3542 TE-16.2/TE-17.1: Removed disabling autonegotiation and explicitly setting port speed a…
  feature/gribi/otg_tests/encap_frr/encap_frr_test.go
  feature/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
Labels: juniper-pr

#3334 Transceiever-5: Added deviation for operational-mode leaf
  feature/platform/transceiver/tests/zr_tunable_parameters_test/metadata.textproto
  feature/platform/transceiver/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr
