Repository openconfig/featureprofiles, pull requests merged in 2024-09, with the labels that each got.

#2996 GNMI-2: gnmi_subscriptionlist_test
  feature/gnmi/subscribe/tests/gnmi_subscriptionlist_test/gnmi_subscriptionlist_test.go
  feature/gnmi/subscribe/tests/gnmi_subscriptionlist_test/metadata.textproto
Labels: juniper-pr, new-requirement-pr

#2938 RT-1.23 : Added extended encoding on OTG ipv6 peers
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/README.md
  feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
Labels: juniper-pr

#2899 TE-1.1 : static_arp_test.go
  feature/interface/staticarp/otg_tests/static_arp_test/README.md
  feature/interface/staticarp/otg_tests/static_arp_test/metadata.textproto
  feature/interface/staticarp/otg_tests/static_arp_test/static_arp_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3009 MGT-1: Updated the script with management vrf name and added deviation for table-connection config
  feature/system/management/otg_tests/management_ha_test/management_ha_test.go
  internal/attrs/attrs.go
Labels: juniper-pr

#3413 RT-5.9 disable_ipv6_nd_ra_test changes incorporated
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/disable_ipv6_nd_ra_test.go
  feature/interface/ip/ipv6_ND/otg_tests/disable_ipv6_nd_ra_test/metadata.textproto
Labels: nokia-pr

#2891 Updates to Transceiver-3:zr_firmware_version_test
  internal/components/components.go
Labels: juniper-pr

#3449 adding 400gzr testbed file to tb mapping
  internal/fptest/runtests.go
Labels: nokia-pr

#3074 Modifications to RT2.13- Weighted-ECMP for IS-IS
  feature/isis/otg_tests/weighted_ecmp_test/metadata.textproto
  feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
Labels: juniper-pr

#2716 OTG TE - 9.1 Changing the test not to update the flows dynamically
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/README.md
  feature/experimental/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/fib_failed_due_to_hw_res_exhaust_test.go
Labels: keysight-pr

#3457 Cisco transceiver 3
  feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/metadata.textproto
  feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/zr_fec_uncorrectable_frames_test.go
  feature/platform/transceiver/tests/zr_firmware_version_test/zr_firmware_version_test.go
  feature/platform/transceiver/tests/zr_tunable_parameters_test/metadata.textproto
  internal/cfgplugins/interface.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3462 Transceiver-9: improving test flow
  feature/platform/transceiver/tests/zr_laser_bias_current_test/zr_laser_bias_current_test.go
Labels: cisco-pr
