Repository openconfig/featureprofiles, pull requests merged in 2025-01, with the labels that each got.

#3671 RT2.12: Minor infrastructure fix
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: nokia-pr

#3550 Adding deviation for isisLevelEnabled, max_ecmp_paths for Juniper routers
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/metadata.textproto
Labels: juniper-pr

#3662 Modified TC5 final port up check as timing was causing flaky results
  feature/interface/holdtime/otg_tests/holdtime_test/README.md
  feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go
Labels: cisco-pr

#3471 SFLOW-1: Configuring sflow collector respective to IPv4 and IPv6
  feature/sflow/otg_tests/sflow_base_test/metadata.textproto
  feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go
  internal/cfgplugins/sflow.go
Labels: nokia-pr

#3144 FP-1.1: Power admin DOWN/UP Test
  feature/platform/tests/power_admin_down_up_test/power_admin_down_up_test.go
Labels: juniper-pr

#3588 RT_14.2 gribi_route_test.go
  feature/gribi/otg_tests/gribi_route_test/gribi_route_test.go
Labels: juniper-pr

#3627 RT_1.23 : bgp_afi_safi_defaults_test.go
  feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
Labels: juniper-pr

#3574 RT-7.11: BGP Policy - Import/Export Policy Action Using Multiple Criteria changes incorporated
  feature/bgp/policybase/otg_tests/import_export_multi_test/README.md
  feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
  feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
Labels: P1, nokia-pr

#3613 RT-1.27: fixed failed tests
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
  internal/cfgplugins/bgp_policy.go
  internal/cfgplugins/tableconnections.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3636 RT-7.4: Updating for deviation usage
  feature/bgp/policybase/otg_tests/aspath_and_community_test/aspath_and_community_test.go
  feature/bgp/policybase/otg_tests/aspath_and_community_test/metadata.textproto
Labels: nokia-pr

#3146 RT-1.23 BGP AFI SAFI OC DEFAULTS TEST changes incorporated.
  feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
  feature/bgp/otg_tests/bgp_afi_safi_defaults/metadata.textproto
Labels: nokia-pr

#2918 OTG: TE 3.7 - Updating the test to run in KNE Env
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: keysight-pr

#3536 [gNMI-1.10] add InterfaceCountersUpdateDelayed deviation
  feature/gnmi/otg_tests/telemetry_basic_check_test/metadata.textproto
  feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
Labels: cisco-pr

#2983 Remove isis_lsp_lifetime_interval_requires_lsp_refresh_interval deviation
  feature/isis/otg_tests/isis_change_lsp_lifetime_test/isis_change_lsp_lifetime_test.go
  feature/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto
  feature/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
  feature/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
  feature/isis/otg_tests/isis_interface_passive_test/metadata.textproto
  feature/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
Labels: arista-pr

#3378 RT-2.12: Remove deviation and remove tag-set naming restriction
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: arista-pr

#2605 System-1: added p4rt capabilities deviation and fixed gnmi call
  feature/system/tests/system_base_test/README.md
  feature/system/tests/system_base_test/g_protocol_test.go
  feature/system/tests/system_base_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr
