Repository openconfig/featureprofiles, pull requests merged in 2025-04, with the labels that each got.

#4090 Credentialz: Add ssh retry mechanism when rotating host parameters
  feature/security/gnsi/credentialz/tests/hiba_authentication/hiba_authentication_test.go
  feature/security/gnsi/credentialz/tests/ssh_password_login_disallowed/ssh_password_login_disallowed_test.go
Labels: nokia-pr

#3865 Policy-forwarding MPLSoGRE encap README
  feature/policy_forwarding/otg_tests/mpls_gre_ipv4_encap_scale_test/README.md
  feature/policy_forwarding/otg_tests/mpls_gre_ipv4_encap_test/README.md
  feature/policy_forwarding/otg_tests/mpls_gre_local_proxy_test/README.md
  testregistry.textproto
Labels: anPF

#3896 Health-1.1: add openconfig as origin for Healthz Get RPC
  feature/system/health/tests/system_generic_health_check/system_generic_health_check_test.go
Labels: cisco-pr

#4088 RT-5.5 Fix to ensure lag interface operational state & infra changes.
  feature/interface/holdtime/otg_tests/holdtime_test/holddown_timers_test.go
Labels: nokia-pr

#4007 TRANSCEIVER-11: Initialized operationalMode & OTN to ETH channel config added
  feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/metadata.textproto
  feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
  internal/cfgplugins/interface.go
Labels: nokia-pr

#4004 TRANSCEIVER-6 Fixed with initializing operationalMode & increased delay
  feature/platform/transceiver/performance_metrics/tests/zr_pm_test/metadata.textproto
  feature/platform/transceiver/performance_metrics/tests/zr_pm_test/zr_pm_test.go
Labels: nokia-pr

#4006 TRANSCEIVER-10 Fixed with operationalMode initialization & OTN to ETH channel config
  feature/platform/transceiver/fec_uncorrectable_frames/tests/zr_fec_uncorrectable_frames_test/metadata.textproto
  feature/platform/transceiver/fec_uncorrectable_frames/tests/zr_fec_uncorrectable_frames_test/zr_fec_uncorrectable_frames_test.go
Labels: nokia-pr

#4003 TRANSCEIVER-5 Fixed with multiple changes
  feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/metadata.textproto
  feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
Labels: nokia-pr

#4029 TRANSCEIVER-13: Fixed by adding deviations & initializing operationalMode
  feature/platform/transceiver/low_power_mode/tests/zr_low_power_mode_test/metadata.textproto
  feature/platform/transceiver/low_power_mode/tests/zr_low_power_mode_test/zr_low_power_mode_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#4108 fixing possible typo in lacp_interval_test.go
  feature/interface/lacp/tests/lacp_interval_test/lacp_interval_test.go
Labels: juniper-pr

#4111 removing deviation skip_controller_card_power_admin
  feature/platform/tests/power_admin_down_up_test/metadata.textproto
Labels: juniper-pr

#4123 removing deviation P4RTModifyTableEntryUnsupported from P4RT-2.2
  feature/p4rt/tests/metadata_validation_test/metadata.textproto
Labels: juniper-pr

#3316 Update RT-2.13: Weighted-ECMP for IS-IS to not also use BGP
  feature/isis/otg_tests/weighted_ecmp_test/README.md
  feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
Labels: keysight-pr

#2894 Updates to Transceiver-8: zr_temprature_test
  feature/platform/transceiver/temperature/tests/zr_temperature_test/zr_temperature_test.go
Labels: juniper-pr

#3739 RT-1.2: BGP Policy & Route Installation changes incorporated
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
Labels: nokia-pr

#3623 Transceiver-4:Changes to zr_input_output_power_test
  feature/platform/transceiver/input_output_power/tests/zr_input_output_power_test/zr_input_output_power_test.go
Labels: juniper-pr

#4142 System1.1
  feature/system/system_base_test/tests/system_banner_test/metadata.textproto
  feature/system/system_base_test/tests/system_banner_test/system_banner_test.go
Labels: cisco-pr

#4160 Modification to "func trafficRXWeights" to calculate the rxPackets by subtracting the traffic received for lag profile
  feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
Labels: juniper-pr

#4101 Gribi route test - Added ipv6 addresses for interfaces
  feature/gribi/otg_tests/gribi_route_test/gribi_route_test.go
Labels: cisco-pr

#4105 zr_tunable_parameters_test: Increased the await time
  feature/platform/transceiver/tunable_parameters/tests/zr_tunable_parameters_test/zr_tunable_parameters_test.go
Labels: juniper-pr

#3447 RT-1.32: BGP policy actions - MED LocPref changes incorporated
  feature/bgp/policybase/otg_tests/actions_med_localpref_prepend_flow_control/actions_MED_LocPref_prepend_flow_control_test.go
Labels: nokia-pr

#4033 TRANSCEIVER-11: changes to zr_logical_channels_test
  feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
  internal/cfgplugins/interface.go
Labels: juniper-pr

#3592 RT-7.2: BGP Policy Community Set changes incorporated
  feature/bgp/policybase/otg_tests/community_test/community_test.go
  feature/bgp/policybase/otg_tests/community_test/metadata.textproto
Labels: nokia-pr

#3620 gNOI-3.1: Changes to complete_chassis_reboot_test
  feature/gnoi/system/tests/complete_chassis_reboot/complete_chassis_reboot_test.go
Labels: juniper-pr

#4041 TRANSCEIVER-9: transceiver component key fix
  feature/platform/transceiver/laser_bias_current/tests/zr_laser_bias_current_test/zr_laser_bias_current_test.go
  feature/platform/transceiver/laser_bias_current/tests/zrp_laser_bias_current_test/zrp_laser_bias_current_test.go
Labels: cisco-pr

#4028 TRANSCEIVER-11: remove stale workaround for optical channel format
  feature/platform/transceiver/logical_channels/tests/zr_logical_channels_test/zr_logical_channels_test.go
  feature/platform/transceiver/logical_channels/tests/zrp_logical_channels_test/zrp_logical_channels_test.go
Labels: cisco-pr
