Repository openconfig/featureprofiles, pull requests merged in 2025-03, with the labels that each got.

#1918 TR-6.2 TestPlan: system logging console
  feature/system/logging/console_vty_file/feature.textproto
  feature/system/logging/console_vty_file/tests/README.md
  feature/system/logging/console_vty_file/tests/metadata.textproto
Labels: documentation, enhancement, P1, WBB Catalog Feature audit

#3867 TE-9.1 fib_failed_due_to_hw_res_exhaust_test.go , changes from pull 2905 merged here
  feature/gribi/otg_tests/fib_failed_due_to_hw_res_exhaust_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3638 TRANSCEIVER-12 Fixed with adding required deviations
  feature/platform/transceiver/supply_voltage/tests/zr_supply_voltage_test/metadata.textproto
  feature/platform/transceiver/supply_voltage/tests/zr_supply_voltage_test/zr_supply_voltage_test.go
  internal/cfgplugins/interface.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3860 Retry gRIBI connection after trigger
  feature/gribi/otg_tests/dut_daemon_failure/dut_daemon_failure_test.go
  feature/gribi/otg_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
  feature/gribi/otg_tests/route_removal_during_failover_test/route_removal_during_failover_test.go
  feature/gribi/otg_tests/supervisor_failure_test/supervisor_failure_test.go
Labels: juniper-pr

#2516 RT-8: Singleton with breakouts
  feature/interface/singleton/tests/singleton_with_breakouts/README.md
  feature/interface/singleton/tests/singleton_with_breakouts/metadata.textproto
  feature/interface/singleton/tests/singleton_with_breakouts/singleton_with_breakouts_test.go
Labels: juniper-pr, new-requirement-pr

#3434 RT-7.8 bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Labels: juniper-pr

#3710 DP-1.14: Updating WRED config as per test requirements
  feature/qos/otg_tests/qos_basic_test/qos_basic_test.go
Labels: juniper-pr

#3640 TRANSCEIVER-7 Added required deviations.
  feature/platform/transceiver/inventory/tests/zr_inventory_test/metadata.textproto
  feature/platform/transceiver/inventory/tests/zr_inventory_test/zr_inventory_test.go
  feature/platform/transceiver/supply_voltage/tests/zr_supply_voltage_test/zr_supply_voltage_test.go
  internal/cfgplugins/interface.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3840 Cisco MPLS-1.1 with included deviations
  feature/mpls/otg_tests/label_block/metadata.textproto
  feature/mpls/otg_tests/label_block/mpls_label_block_with_isis_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3979 Test to cover system/logging for console, VTY and files
  feature/system/logging/console_vty_file/feature.textproto
  feature/system/logging/otg_tests/console_vty_file/README.md
  feature/system/logging/otg_tests/console_vty_file/console_vty_file_test.go
  feature/system/logging/otg_tests/console_vty_file/metadata.textproto
Labels: anCX, ngPR

#3969 TRANSCEIVER-1 fixed metadata & initialized operationalMode
  feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/metadata.textproto
  feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/zr_cd_test.go
Labels: nokia-pr

#4005 TRANSCEIVER-8 Fixed with operationalMode inititization
  feature/platform/transceiver/temperature/tests/zr_temperature_test/metadata.textproto
  feature/platform/transceiver/temperature/tests/zr_temperature_test/zr_temperature_test.go
Labels: nokia-pr

#3976 TRANSCEIVER-4: Added InterfaceConfig & increased delay for telemetry
  feature/platform/transceiver/input_output_power/tests/zr_input_output_power_test/metadata.textproto
  feature/platform/transceiver/input_output_power/tests/zr_input_output_power_test/zr_input_output_power_test.go
Labels: nokia-pr

#3973 RT-2.1 changes
  feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3395 RT-1.27 : static_route_bgp_redistribution_test.go
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
  internal/cfgplugins/bgp_policy.go
Labels: juniper-pr

#3632 RT-7.3: Fixing IPv6 route generation, DefaultImportPolicy and regexp pattern
  feature/bgp/policybase/otg_tests/aspath_test/aspath_test.go
  feature/bgp/policybase/otg_tests/aspath_test/metadata.textproto
Labels: nokia-pr

#3611 RT-7.5 Fixed timing of policy application & peergroup configurations
  feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
  feature/bgp/policybase/otg_tests/link_bandwidth_test/metadata.textproto
Labels: P1, nokia-pr

#2147 RT-5.1: Singleton Interface - Enhancement by Test Case 2 and Test Case 3
  feature/interface/singleton/otg_tests/singleton_test/README.md
Labels: enhancement, P1

#4052 Removed 'explicit_port_speed' deviations from remaining files.
  feature/aft/afts_summary/otg_tests/scale_aft_summary/metadata.textproto
  feature/bgp/bgp_session_mode/otg_tests/bgp_session_mode_configuration_test/metadata.textproto
  feature/gribi/otg_tests/gribi_route_test/metadata.textproto
  feature/interface/lacp/tests/lacp_interval_test/metadata.textproto
  feature/mtu/otg_tests/pmtu_handing/metadata.textproto
Labels: nokia-pr

#3430 Modifications to RT2.12, Static route to IS-IS redistribution
  feature/isis/otg_tests/static_route_isis_redistribution/metadata.textproto
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: juniper-pr

#3972 asoman/anpfGREdecap
  feature/policy_forwarding/otg_tests/mpls_gre_ipv4_decap_scale_test/README.md
  feature/policy_forwarding/otg_tests/mpls_gre_ipv4_decap_test/README.md
  testregistry.textproto
Labels: anPF
