Repository openconfig/featureprofiles, pull requests merged in 2025-05, with the labels that each got.

#3532 RT-1.30: BGP nested import/export policy attachment changes incorporated
  feature/bgp/policybase/otg_tests/nested_policies/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
Labels: nokia-pr

#3698 RT-7.11: BGP Policy - Import/Export Policy Changes related to MedAction implemented.
  feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
Labels: nokia-pr

#2907 RT-7.5 : link_bandwidth_test
  feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
  feature/bgp/policybase/otg_tests/link_bandwidth_test/metadata.textproto
Labels: juniper-pr

#3505 RT-1.29: BGP chained import/export policy attachment changes incorpor…
  feature/bgp/policybase/otg_tests/chained_policies_test/README.md
  feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
  feature/bgp/policybase/otg_tests/chained_policies_test/metadata.textproto
Labels: P1, nokia-pr

#3564 BGP internal/external distance deviation
  feature/bgp/admin_distance/otg_tests/admin_distance_test/admin_distance_test.go
  feature/bgp/admin_distance/otg_tests/admin_distance_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#3956 RT:2.1: Enabling deviation isis_explicit_level_authentication_config
  feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
Labels: nokia-pr

#3759 RT-5.8: IPv6 Link Local: Added Sleep of 15sec after start traffic to have the got packets flow in DUT.
  feature/interface/ip/ipv6_link_local/otg_tests/ipv6_link_local_test/ipv6_link_local_test.go
Labels: juniper-pr

#4122 DP-1.2: Fixing Validation of /qos/interfaces/interface/output/queues/queue/state/name with Queue Name instead of Forwarding Group
  feature/qos/tests/qos_policy_config_test/qos_policy_config_test.go
Labels: juniper-pr

#4168 Adding deviation
  feature/bgp/routereflector/otg_tests/route_reflector_scale/metadata.textproto
Labels: juniper-pr

#3734 TE-11.21: Backup NHG: Multiple NH with PBF changes incorporated
  feature/gribi/otg_tests/backup_nhg_multiple_nh_pbf_test/README.md
  feature/gribi/otg_tests/backup_nhg_multiple_nh_pbf_test/backup_nhg_multiple_nh_pbf_test.go
Labels: nokia-pr

#2902 RT-1.14: Added code to proceed with BGP config based on interface status.
  feature/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
Labels: juniper-pr, anCX

#3575 RT_7.8 changes and deviation
  feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Labels: cisco-pr

#2005 TUN-1.3 Interface based IPv4 GRE Encapsulation
  feature/tunnel/otg_tests/tunnel_interface_based_ipv4_gre_encapsulation_test/README.md
  feature/tunnel/otg_tests/tunnel_interface_based_ipv4_gre_encapsulation_test/metadata.textproto
  feature/tunnel/otg_tests/tunnel_interface_based_ipv4_gre_encapsulation_test/tunnel_interface_based_ipv4_gre_encapsulation_test.go
Labels: juniper-pr, anCX, new-requirement-pr

#4180 RT-2.12: Replaced GetAll with WatchAll & fixed watchAll conditions
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: nokia-pr

#4089 Fix Vendor OCAGENT procname in gnoi.go
  internal/gnoi/gnoi.go
Labels: nokia-pr

#3709 acctz-3.1 fix start/stop accounting check
  feature/security/gnsi/acctz/tests/record_subscribe_non_grpc/record_subscribe_non_grpc_test.go
Labels: nokia-pr

#4207 fix basic_encap_test
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
  feature/gribi/otg_tests/basic_encap_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: google-pr

#4210 Adding deviation for set-med-action
  feature/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
  feature/bgp/ate_tests/bgp_long_lived_graceful_restart/metadata.textproto
  feature/bgp/otg_tests/bgp_always_compare_med/bgp_always_compare_med_test.go
  feature/bgp/otg_tests/bgp_always_compare_med/metadata.textproto
  feature/bgp/policybase/otg_tests/actions_med_localpref_prepend_flow_control/actions_MED_LocPref_prepend_flow_control_test.go
  feature/bgp/policybase/otg_tests/actions_med_localpref_prepend_flow_control/metadata.textproto
  feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
  feature/bgp/policybase/otg_tests/chained_policies_test/metadata.textproto
  feature/bgp/policybase/otg_tests/import_export_multi_test/import_export_multi_test.go
  feature/bgp/policybase/otg_tests/import_export_multi_test/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/metadata.textproto
  feature/bgp/policybase/otg_tests/nested_policies/nested_policies_test.go
  feature/bgp/policybase/otg_tests/route_installation_test/metadata.textproto
  feature/bgp/policybase/otg_tests/route_installation_test/route_installation_test.go
  feature/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/drained_configuration_convergence_time_bgp_test.go
  feature/system/gnmi/benchmarking/otg_tests/drained_configuration_convergence_time/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#4124 RT-2.13 Adding MaxECMP Paths and Deviations
  feature/isis/otg_tests/weighted_ecmp_test/README.md
  feature/isis/otg_tests/weighted_ecmp_test/metadata.textproto
  feature/isis/otg_tests/weighted_ecmp_test/weighted_ecmp_test.go
Labels: nokia-pr

#4213 Modification to RT2.12-static_route_isis_redistribution_test.go
  feature/isis/otg_tests/static_route_isis_redistribution/metadata.textproto
  feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
Labels: juniper-pr

#3431 TE-16.1: adding defer flush to leave device clean of AFT entries
  feature/gribi/otg_tests/basic_encap_test/basic_encap_test.go
Labels: cisco-pr

#4172 removing deviation
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr
