Repository openconfig/featureprofiles, pull requests merged in 2025-07, with the labels that each got.

#4299 RT-4.10 Add delay after OTG config
  feature/aft/afts_summary/otg_tests/route_summary_counters_test/route_summary_counters_test.go
Labels: nokia-pr

#4283 RT-7.5 link_bandwidth_test.go
  feature/bgp/policybase/otg_tests/link_bandwidth_test/README.md
  feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
Labels: juniper-pr

#4204 RT-1.27 static_route_bgp_redistribution_test.go
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/README.md
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#4196 TE-17.1 vrf_policy_driven_te_test.go
  feature/gribi/otg_tests/vrf_policy_driven_te/README.md
  feature/gribi/otg_tests/vrf_policy_driven_te/metadata.textproto
  feature/gribi/otg_tests/vrf_policy_driven_te/vrf_policy_driven_te_test.go
Labels: juniper-pr

#4281 RT-1.5 bgp_prefix_limit_test.go
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/README.md
  feature/bgp/prefixlimit/otg_tests/bgp_prefix_limit_test/bgp_prefix_limit_test.go
Labels: juniper-pr

#4297 RT-2.14: Added MaxEcmpPaths & increased time duration
  feature/isis/otg_tests/isis_drain_test/README.md
  feature/isis/otg_tests/isis_drain_test/isis_drain_test.go
Labels: nokia-pr

#4367 deviated removed for RT-2.1
  feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
Labels: cisco-pr

#4342 RT-1.27: Enabling default_bgp_instance_name and fixing recent changes
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto
  feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
Labels: nokia-pr

#4263 RT-7.8: comm_match_action_test changes incorporated.
  feature/bgp/policybase/otg_tests/comm_match_action_test/README.md
  feature/bgp/policybase/otg_tests/comm_match_action_test/bgp_comm_match_action_test.go
  feature/bgp/policybase/otg_tests/comm_match_action_test/metadata.textproto
Labels: nokia-pr

#4357 Added deviation non_interval_fec_error_counter for Juniper
  feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/metadata.textproto
  feature/platform/transceiver/tests/zr_fec_uncorrectable_frames_test/zr_fec_uncorrectable_frames_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#4187 OC-26.1 Deviation ntp_source_address_unsupported
  feature/system/ntp/tests/system_ntp_test/metadata.textproto
  feature/system/ntp/tests/system_ntp_test/system_ntp_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: cisco-pr

#4141 RT-2.15: Creating Test for IS-IS Extensions for Segment Routing
  feature/isis/otg_tests/isis_extensions_segment_routing_test/isis_extensions_segment_routing_test.go
  feature/isis/otg_tests/isis_extensions_segment_routing_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: keysight-pr

#4082 TE3.7 - Added remove config end of testImplementDrain and addconfig at start of testBaseHierarchialNHGwithVrfPolW test.
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Labels: cisco-pr

#4436 Update inner_ttl_ipv4 README to remove match condition on destination IP and add more details on test procedure
  feature/policy_forwarding/encapsulation/otg_tests/inner_ttl_ipv4/README.md
Labels: anPF

#4447 Multiple VRFs and GUE DECAP in Default VRF Readme
  feature/policy_forwarding/vrf_selection/otg_tests/base_vrf_selection/README.md
  feature/policy_forwarding/vrf_selection/otg_tests/base_vrf_selection/base_vrf_selection_test.go
  feature/policy_forwarding/vrf_selection/otg_tests/base_vrf_selection/metadata.textproto
  feature/policy_forwarding/vrf_selection/otg_tests/multiple_vrfs_and_gue_decap/README.md
  feature/policy_forwarding/vrf_selection/otg_tests/multiple_vrfs_and_gue_decap/metadata.textproto
  feature/policy_forwarding/vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/README.md
  feature/policy_forwarding/vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/metadata.textproto
  feature/policy_forwarding/vrf_selection/otg_tests/protocol_dscp_rules_for_vrf_selection_test/protocol_dscp_rules_for_vrf_selection_test.go
Labels: keysight-pr, gIRO
