Repository openconfig/featureprofiles, pull requests merged in 2025-02, with the labels that each got.

#3748 zr_cd_test:added code to close streams
  feature/platform/transceiver/chromatic_dispersion/tests/zr_cd_test/zr_cd_test.go
Labels: juniper-pr

#3738 added ISIS p2p circuit type and hello timer sub tests
  feature/isis/otg_tests/base_adjacencies_test/README.md
  feature/isis/otg_tests/base_adjacencies_test/base_adjacencies_test.go
  feature/isis/otg_tests/base_adjacencies_test/metadata.textproto
Labels: google-pr

#3555 deviation fix for P4RT-3.21
  feature/p4rt/otg_tests/google_discovery_protocol_packetout_lag_test/google_discovery_protocol_packetout_lag_test.go
Labels: juniper-pr

#3346 RT 1.24: Updated the script with default policy behavior for BGP external and internal neighbors
  feature/bgp/otg_tests/bgp_2byte_4byte_asn_policy_test/bgp_2byte_4byte_asn_policy_test.go
Labels: juniper-pr

#3347 TE-9.2: Added deviation static_lsp_unsupported
  feature/gribi/otg_tests/static_lsp_test/metadata.textproto
  feature/gribi/otg_tests/static_lsp_test/static_lsp_test.go
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3631 RT-1.53 : prefix_set_test.go
  feature/policy_forwarding/otg_tests/prefix_set_test/metadata.textproto
  feature/policy_forwarding/otg_tests/prefix_set_test/prefix_set_test.go
  internal/deviations/deviations.go
  internal/gnoi/gnoi.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr

#3723 RT_1.54 bgp_override_as_path_split_horizon_test.go
  feature/bgp/otg_tests/bgp_override_as_path_split_horizon_test/bgp_override_as_path_split_horizon_test.go
Labels: juniper-pr

#3814 Removing skip_pbf_with_decap_encap_vrf deviation
  feature/gribi/otg_tests/backup_nhg_action_pbf/backup_nhg_action_pbf_test.go
  feature/gribi/otg_tests/backup_nhg_multiple_nh_pbf_test/backup_nhg_multiple_nh_pbf_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
  feature/gribi/otg_tests/base_hierarchical_nhg_update/metadata.textproto
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
  feature/gribi/otg_tests/base_hierarchical_route_installation_test/metadata.textproto
  internal/deviations/deviations.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: nokia-pr

#3753 System-1: fix empty banner test
  feature/system/system_base_test/tests/system_banner_test/system_banner_test.go
Labels: nokia-pr

#3693 Health 1.1 system_generic_health_check
  feature/system/health/tests/system_generic_health_check/metadata.textproto
  feature/system/health/tests/system_generic_health_check/system_generic_health_check_test.go
Labels: juniper-pr

#3844 RT-2.14 | Changes to isis drain test
  feature/isis/otg_tests/isis_drain_test/isis_drain_test.go
  feature/isis/otg_tests/isis_drain_test/metadata.textproto
Labels: cisco-pr

#3833 Added deviation for GetOnStateUnsupported
  feature/system/system_base_test/tests/system_g_protocol_test/metadata.textproto
  feature/system/system_base_test/tests/system_g_protocol_test/system_g_protocol_test.go
  proto/metadata.proto
  proto/metadata_go_proto/metadata.pb.go
Labels: juniper-pr
